// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newDefAction(db *gorm.DB, opts ...gen.DOOption) defAction {
	_defAction := defAction{}

	_defAction.defActionDo.UseDB(db, opts...)
	_defAction.defActionDo.UseModel(&model.DefAction{})

	tableName := _defAction.defActionDo.TableName()
	_defAction.ALL = field.NewAsterisk(tableName)
	_defAction.ActionID = field.NewString(tableName, "action_id")
	_defAction.ActionCode = field.NewString(tableName, "action_code")
	_defAction.ActionName = field.NewString(tableName, "action_name")
	_defAction.ActionType = field.NewString(tableName, "action_type")
	_defAction.InvokeURL = field.NewString(tableName, "invoke_url")
	_defAction.InvokeMethod = field.NewString(tableName, "invoke_method")
	_defAction.InvokeType = field.NewString(tableName, "invoke_type")
	_defAction.Status = field.NewString(tableName, "status")
	_defAction.Created = field.NewTime(tableName, "created")
	_defAction.CreatedBy = field.NewString(tableName, "created_by")
	_defAction.LastUpd = field.NewTime(tableName, "last_upd")
	_defAction.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_defAction.fillFieldMap()

	return _defAction
}

type defAction struct {
	defActionDo defActionDo

	ALL          field.Asterisk
	ActionID     field.String
	ActionCode   field.String
	ActionName   field.String
	ActionType   field.String
	InvokeURL    field.String
	InvokeMethod field.String
	InvokeType   field.String
	Status       field.String
	Created      field.Time
	CreatedBy    field.String
	LastUpd      field.Time
	LastUpdBy    field.String

	fieldMap map[string]field.Expr
}

func (d defAction) Table(newTableName string) *defAction {
	d.defActionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d defAction) As(alias string) *defAction {
	d.defActionDo.DO = *(d.defActionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *defAction) updateTableName(table string) *defAction {
	d.ALL = field.NewAsterisk(table)
	d.ActionID = field.NewString(table, "action_id")
	d.ActionCode = field.NewString(table, "action_code")
	d.ActionName = field.NewString(table, "action_name")
	d.ActionType = field.NewString(table, "action_type")
	d.InvokeURL = field.NewString(table, "invoke_url")
	d.InvokeMethod = field.NewString(table, "invoke_method")
	d.InvokeType = field.NewString(table, "invoke_type")
	d.Status = field.NewString(table, "status")
	d.Created = field.NewTime(table, "created")
	d.CreatedBy = field.NewString(table, "created_by")
	d.LastUpd = field.NewTime(table, "last_upd")
	d.LastUpdBy = field.NewString(table, "last_upd_by")

	d.fillFieldMap()

	return d
}

func (d *defAction) WithContext(ctx context.Context) IDefActionDo {
	return d.defActionDo.WithContext(ctx)
}

func (d defAction) TableName() string { return d.defActionDo.TableName() }

func (d defAction) Alias() string { return d.defActionDo.Alias() }

func (d defAction) Columns(cols ...field.Expr) gen.Columns { return d.defActionDo.Columns(cols...) }

func (d *defAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *defAction) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 12)
	d.fieldMap["action_id"] = d.ActionID
	d.fieldMap["action_code"] = d.ActionCode
	d.fieldMap["action_name"] = d.ActionName
	d.fieldMap["action_type"] = d.ActionType
	d.fieldMap["invoke_url"] = d.InvokeURL
	d.fieldMap["invoke_method"] = d.InvokeMethod
	d.fieldMap["invoke_type"] = d.InvokeType
	d.fieldMap["status"] = d.Status
	d.fieldMap["created"] = d.Created
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["last_upd"] = d.LastUpd
	d.fieldMap["last_upd_by"] = d.LastUpdBy
}

func (d defAction) clone(db *gorm.DB) defAction {
	d.defActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d defAction) replaceDB(db *gorm.DB) defAction {
	d.defActionDo.ReplaceDB(db)
	return d
}

type defActionDo struct{ gen.DO }

type IDefActionDo interface {
	gen.SubQuery
	Debug() IDefActionDo
	WithContext(ctx context.Context) IDefActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDefActionDo
	WriteDB() IDefActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDefActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDefActionDo
	Not(conds ...gen.Condition) IDefActionDo
	Or(conds ...gen.Condition) IDefActionDo
	Select(conds ...field.Expr) IDefActionDo
	Where(conds ...gen.Condition) IDefActionDo
	Order(conds ...field.Expr) IDefActionDo
	Distinct(cols ...field.Expr) IDefActionDo
	Omit(cols ...field.Expr) IDefActionDo
	Join(table schema.Tabler, on ...field.Expr) IDefActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDefActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDefActionDo
	Group(cols ...field.Expr) IDefActionDo
	Having(conds ...gen.Condition) IDefActionDo
	Limit(limit int) IDefActionDo
	Offset(offset int) IDefActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDefActionDo
	Unscoped() IDefActionDo
	Create(values ...*model.DefAction) error
	CreateInBatches(values []*model.DefAction, batchSize int) error
	Save(values ...*model.DefAction) error
	First() (*model.DefAction, error)
	Take() (*model.DefAction, error)
	Last() (*model.DefAction, error)
	Find() ([]*model.DefAction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefAction, err error)
	FindInBatches(result *[]*model.DefAction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DefAction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDefActionDo
	Assign(attrs ...field.AssignExpr) IDefActionDo
	Joins(fields ...field.RelationField) IDefActionDo
	Preload(fields ...field.RelationField) IDefActionDo
	FirstOrInit() (*model.DefAction, error)
	FirstOrCreate() (*model.DefAction, error)
	FindByPage(offset int, limit int) (result []*model.DefAction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDefActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d defActionDo) Debug() IDefActionDo {
	return d.withDO(d.DO.Debug())
}

func (d defActionDo) WithContext(ctx context.Context) IDefActionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d defActionDo) ReadDB() IDefActionDo {
	return d.Clauses(dbresolver.Read)
}

func (d defActionDo) WriteDB() IDefActionDo {
	return d.Clauses(dbresolver.Write)
}

func (d defActionDo) Session(config *gorm.Session) IDefActionDo {
	return d.withDO(d.DO.Session(config))
}

func (d defActionDo) Clauses(conds ...clause.Expression) IDefActionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d defActionDo) Returning(value interface{}, columns ...string) IDefActionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d defActionDo) Not(conds ...gen.Condition) IDefActionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d defActionDo) Or(conds ...gen.Condition) IDefActionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d defActionDo) Select(conds ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d defActionDo) Where(conds ...gen.Condition) IDefActionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d defActionDo) Order(conds ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d defActionDo) Distinct(cols ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d defActionDo) Omit(cols ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d defActionDo) Join(table schema.Tabler, on ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d defActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d defActionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d defActionDo) Group(cols ...field.Expr) IDefActionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d defActionDo) Having(conds ...gen.Condition) IDefActionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d defActionDo) Limit(limit int) IDefActionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d defActionDo) Offset(offset int) IDefActionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d defActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDefActionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d defActionDo) Unscoped() IDefActionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d defActionDo) Create(values ...*model.DefAction) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d defActionDo) CreateInBatches(values []*model.DefAction, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d defActionDo) Save(values ...*model.DefAction) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d defActionDo) First() (*model.DefAction, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefAction), nil
	}
}

func (d defActionDo) Take() (*model.DefAction, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefAction), nil
	}
}

func (d defActionDo) Last() (*model.DefAction, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefAction), nil
	}
}

func (d defActionDo) Find() ([]*model.DefAction, error) {
	result, err := d.DO.Find()
	return result.([]*model.DefAction), err
}

func (d defActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefAction, err error) {
	buf := make([]*model.DefAction, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d defActionDo) FindInBatches(result *[]*model.DefAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d defActionDo) Attrs(attrs ...field.AssignExpr) IDefActionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d defActionDo) Assign(attrs ...field.AssignExpr) IDefActionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d defActionDo) Joins(fields ...field.RelationField) IDefActionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d defActionDo) Preload(fields ...field.RelationField) IDefActionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d defActionDo) FirstOrInit() (*model.DefAction, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefAction), nil
	}
}

func (d defActionDo) FirstOrCreate() (*model.DefAction, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefAction), nil
	}
}

func (d defActionDo) FindByPage(offset int, limit int) (result []*model.DefAction, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d defActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d defActionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d defActionDo) Delete(models ...*model.DefAction) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *defActionDo) withDO(do gen.Dao) *defActionDo {
	d.DO = *do.(*gen.DO)
	return d
}
