// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newDefGroup(db *gorm.DB, opts ...gen.DOOption) defGroup {
	_defGroup := defGroup{}

	_defGroup.defGroupDo.UseDB(db, opts...)
	_defGroup.defGroupDo.UseModel(&model.DefGroup{})

	tableName := _defGroup.defGroupDo.TableName()
	_defGroup.ALL = field.NewAsterisk(tableName)
	_defGroup.GroupID = field.NewString(tableName, "group_id")
	_defGroup.GroupCode = field.NewString(tableName, "group_code")
	_defGroup.GroupName = field.NewString(tableName, "group_name")
	_defGroup.Status = field.NewString(tableName, "status")
	_defGroup.CreatedBy = field.NewString(tableName, "created_by")
	_defGroup.Created = field.NewTime(tableName, "created")
	_defGroup.LastUpdBy = field.NewString(tableName, "last_upd_by")
	_defGroup.LastUpd = field.NewTime(tableName, "last_upd")

	_defGroup.fillFieldMap()

	return _defGroup
}

type defGroup struct {
	defGroupDo defGroupDo

	ALL       field.Asterisk
	GroupID   field.String
	GroupCode field.String
	GroupName field.String
	Status    field.String
	CreatedBy field.String
	Created   field.Time
	LastUpdBy field.String
	LastUpd   field.Time

	fieldMap map[string]field.Expr
}

func (d defGroup) Table(newTableName string) *defGroup {
	d.defGroupDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d defGroup) As(alias string) *defGroup {
	d.defGroupDo.DO = *(d.defGroupDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *defGroup) updateTableName(table string) *defGroup {
	d.ALL = field.NewAsterisk(table)
	d.GroupID = field.NewString(table, "group_id")
	d.GroupCode = field.NewString(table, "group_code")
	d.GroupName = field.NewString(table, "group_name")
	d.Status = field.NewString(table, "status")
	d.CreatedBy = field.NewString(table, "created_by")
	d.Created = field.NewTime(table, "created")
	d.LastUpdBy = field.NewString(table, "last_upd_by")
	d.LastUpd = field.NewTime(table, "last_upd")

	d.fillFieldMap()

	return d
}

func (d *defGroup) WithContext(ctx context.Context) IDefGroupDo { return d.defGroupDo.WithContext(ctx) }

func (d defGroup) TableName() string { return d.defGroupDo.TableName() }

func (d defGroup) Alias() string { return d.defGroupDo.Alias() }

func (d defGroup) Columns(cols ...field.Expr) gen.Columns { return d.defGroupDo.Columns(cols...) }

func (d *defGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *defGroup) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["group_id"] = d.GroupID
	d.fieldMap["group_code"] = d.GroupCode
	d.fieldMap["group_name"] = d.GroupName
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["created"] = d.Created
	d.fieldMap["last_upd_by"] = d.LastUpdBy
	d.fieldMap["last_upd"] = d.LastUpd
}

func (d defGroup) clone(db *gorm.DB) defGroup {
	d.defGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d defGroup) replaceDB(db *gorm.DB) defGroup {
	d.defGroupDo.ReplaceDB(db)
	return d
}

type defGroupDo struct{ gen.DO }

type IDefGroupDo interface {
	gen.SubQuery
	Debug() IDefGroupDo
	WithContext(ctx context.Context) IDefGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDefGroupDo
	WriteDB() IDefGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDefGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDefGroupDo
	Not(conds ...gen.Condition) IDefGroupDo
	Or(conds ...gen.Condition) IDefGroupDo
	Select(conds ...field.Expr) IDefGroupDo
	Where(conds ...gen.Condition) IDefGroupDo
	Order(conds ...field.Expr) IDefGroupDo
	Distinct(cols ...field.Expr) IDefGroupDo
	Omit(cols ...field.Expr) IDefGroupDo
	Join(table schema.Tabler, on ...field.Expr) IDefGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDefGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDefGroupDo
	Group(cols ...field.Expr) IDefGroupDo
	Having(conds ...gen.Condition) IDefGroupDo
	Limit(limit int) IDefGroupDo
	Offset(offset int) IDefGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDefGroupDo
	Unscoped() IDefGroupDo
	Create(values ...*model.DefGroup) error
	CreateInBatches(values []*model.DefGroup, batchSize int) error
	Save(values ...*model.DefGroup) error
	First() (*model.DefGroup, error)
	Take() (*model.DefGroup, error)
	Last() (*model.DefGroup, error)
	Find() ([]*model.DefGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefGroup, err error)
	FindInBatches(result *[]*model.DefGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DefGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDefGroupDo
	Assign(attrs ...field.AssignExpr) IDefGroupDo
	Joins(fields ...field.RelationField) IDefGroupDo
	Preload(fields ...field.RelationField) IDefGroupDo
	FirstOrInit() (*model.DefGroup, error)
	FirstOrCreate() (*model.DefGroup, error)
	FindByPage(offset int, limit int) (result []*model.DefGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDefGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d defGroupDo) Debug() IDefGroupDo {
	return d.withDO(d.DO.Debug())
}

func (d defGroupDo) WithContext(ctx context.Context) IDefGroupDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d defGroupDo) ReadDB() IDefGroupDo {
	return d.Clauses(dbresolver.Read)
}

func (d defGroupDo) WriteDB() IDefGroupDo {
	return d.Clauses(dbresolver.Write)
}

func (d defGroupDo) Session(config *gorm.Session) IDefGroupDo {
	return d.withDO(d.DO.Session(config))
}

func (d defGroupDo) Clauses(conds ...clause.Expression) IDefGroupDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d defGroupDo) Returning(value interface{}, columns ...string) IDefGroupDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d defGroupDo) Not(conds ...gen.Condition) IDefGroupDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d defGroupDo) Or(conds ...gen.Condition) IDefGroupDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d defGroupDo) Select(conds ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d defGroupDo) Where(conds ...gen.Condition) IDefGroupDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d defGroupDo) Order(conds ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d defGroupDo) Distinct(cols ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d defGroupDo) Omit(cols ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d defGroupDo) Join(table schema.Tabler, on ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d defGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d defGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d defGroupDo) Group(cols ...field.Expr) IDefGroupDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d defGroupDo) Having(conds ...gen.Condition) IDefGroupDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d defGroupDo) Limit(limit int) IDefGroupDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d defGroupDo) Offset(offset int) IDefGroupDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d defGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDefGroupDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d defGroupDo) Unscoped() IDefGroupDo {
	return d.withDO(d.DO.Unscoped())
}

func (d defGroupDo) Create(values ...*model.DefGroup) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d defGroupDo) CreateInBatches(values []*model.DefGroup, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d defGroupDo) Save(values ...*model.DefGroup) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d defGroupDo) First() (*model.DefGroup, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefGroup), nil
	}
}

func (d defGroupDo) Take() (*model.DefGroup, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefGroup), nil
	}
}

func (d defGroupDo) Last() (*model.DefGroup, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefGroup), nil
	}
}

func (d defGroupDo) Find() ([]*model.DefGroup, error) {
	result, err := d.DO.Find()
	return result.([]*model.DefGroup), err
}

func (d defGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefGroup, err error) {
	buf := make([]*model.DefGroup, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d defGroupDo) FindInBatches(result *[]*model.DefGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d defGroupDo) Attrs(attrs ...field.AssignExpr) IDefGroupDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d defGroupDo) Assign(attrs ...field.AssignExpr) IDefGroupDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d defGroupDo) Joins(fields ...field.RelationField) IDefGroupDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d defGroupDo) Preload(fields ...field.RelationField) IDefGroupDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d defGroupDo) FirstOrInit() (*model.DefGroup, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefGroup), nil
	}
}

func (d defGroupDo) FirstOrCreate() (*model.DefGroup, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefGroup), nil
	}
}

func (d defGroupDo) FindByPage(offset int, limit int) (result []*model.DefGroup, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d defGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d defGroupDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d defGroupDo) Delete(models ...*model.DefGroup) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *defGroupDo) withDO(do gen.Dao) *defGroupDo {
	d.DO = *do.(*gen.DO)
	return d
}
