// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newDefCondition(db *gorm.DB, opts ...gen.DOOption) defCondition {
	_defCondition := defCondition{}

	_defCondition.defConditionDo.UseDB(db, opts...)
	_defCondition.defConditionDo.UseModel(&model.DefCondition{})

	tableName := _defCondition.defConditionDo.TableName()
	_defCondition.ALL = field.NewAsterisk(tableName)
	_defCondition.ConditionID = field.NewString(tableName, "condition_id")
	_defCondition.ConditionCode = field.NewString(tableName, "condition_code")
	_defCondition.ConditionName = field.NewString(tableName, "condition_name")
	_defCondition.ConditionType = field.NewString(tableName, "condition_type")
	_defCondition.Status = field.NewString(tableName, "status")
	_defCondition.Created = field.NewTime(tableName, "created")
	_defCondition.CreatedBy = field.NewString(tableName, "created_by")
	_defCondition.LastUpd = field.NewTime(tableName, "last_upd")
	_defCondition.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_defCondition.fillFieldMap()

	return _defCondition
}

type defCondition struct {
	defConditionDo defConditionDo

	ALL           field.Asterisk
	ConditionID   field.String
	ConditionCode field.String
	ConditionName field.String
	ConditionType field.String
	Status        field.String
	Created       field.Time
	CreatedBy     field.String
	LastUpd       field.Time
	LastUpdBy     field.String

	fieldMap map[string]field.Expr
}

func (d defCondition) Table(newTableName string) *defCondition {
	d.defConditionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d defCondition) As(alias string) *defCondition {
	d.defConditionDo.DO = *(d.defConditionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *defCondition) updateTableName(table string) *defCondition {
	d.ALL = field.NewAsterisk(table)
	d.ConditionID = field.NewString(table, "condition_id")
	d.ConditionCode = field.NewString(table, "condition_code")
	d.ConditionName = field.NewString(table, "condition_name")
	d.ConditionType = field.NewString(table, "condition_type")
	d.Status = field.NewString(table, "status")
	d.Created = field.NewTime(table, "created")
	d.CreatedBy = field.NewString(table, "created_by")
	d.LastUpd = field.NewTime(table, "last_upd")
	d.LastUpdBy = field.NewString(table, "last_upd_by")

	d.fillFieldMap()

	return d
}

func (d *defCondition) WithContext(ctx context.Context) IDefConditionDo {
	return d.defConditionDo.WithContext(ctx)
}

func (d defCondition) TableName() string { return d.defConditionDo.TableName() }

func (d defCondition) Alias() string { return d.defConditionDo.Alias() }

func (d defCondition) Columns(cols ...field.Expr) gen.Columns {
	return d.defConditionDo.Columns(cols...)
}

func (d *defCondition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *defCondition) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["condition_id"] = d.ConditionID
	d.fieldMap["condition_code"] = d.ConditionCode
	d.fieldMap["condition_name"] = d.ConditionName
	d.fieldMap["condition_type"] = d.ConditionType
	d.fieldMap["status"] = d.Status
	d.fieldMap["created"] = d.Created
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["last_upd"] = d.LastUpd
	d.fieldMap["last_upd_by"] = d.LastUpdBy
}

func (d defCondition) clone(db *gorm.DB) defCondition {
	d.defConditionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d defCondition) replaceDB(db *gorm.DB) defCondition {
	d.defConditionDo.ReplaceDB(db)
	return d
}

type defConditionDo struct{ gen.DO }

type IDefConditionDo interface {
	gen.SubQuery
	Debug() IDefConditionDo
	WithContext(ctx context.Context) IDefConditionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDefConditionDo
	WriteDB() IDefConditionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDefConditionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDefConditionDo
	Not(conds ...gen.Condition) IDefConditionDo
	Or(conds ...gen.Condition) IDefConditionDo
	Select(conds ...field.Expr) IDefConditionDo
	Where(conds ...gen.Condition) IDefConditionDo
	Order(conds ...field.Expr) IDefConditionDo
	Distinct(cols ...field.Expr) IDefConditionDo
	Omit(cols ...field.Expr) IDefConditionDo
	Join(table schema.Tabler, on ...field.Expr) IDefConditionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDefConditionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDefConditionDo
	Group(cols ...field.Expr) IDefConditionDo
	Having(conds ...gen.Condition) IDefConditionDo
	Limit(limit int) IDefConditionDo
	Offset(offset int) IDefConditionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDefConditionDo
	Unscoped() IDefConditionDo
	Create(values ...*model.DefCondition) error
	CreateInBatches(values []*model.DefCondition, batchSize int) error
	Save(values ...*model.DefCondition) error
	First() (*model.DefCondition, error)
	Take() (*model.DefCondition, error)
	Last() (*model.DefCondition, error)
	Find() ([]*model.DefCondition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefCondition, err error)
	FindInBatches(result *[]*model.DefCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DefCondition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDefConditionDo
	Assign(attrs ...field.AssignExpr) IDefConditionDo
	Joins(fields ...field.RelationField) IDefConditionDo
	Preload(fields ...field.RelationField) IDefConditionDo
	FirstOrInit() (*model.DefCondition, error)
	FirstOrCreate() (*model.DefCondition, error)
	FindByPage(offset int, limit int) (result []*model.DefCondition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDefConditionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d defConditionDo) Debug() IDefConditionDo {
	return d.withDO(d.DO.Debug())
}

func (d defConditionDo) WithContext(ctx context.Context) IDefConditionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d defConditionDo) ReadDB() IDefConditionDo {
	return d.Clauses(dbresolver.Read)
}

func (d defConditionDo) WriteDB() IDefConditionDo {
	return d.Clauses(dbresolver.Write)
}

func (d defConditionDo) Session(config *gorm.Session) IDefConditionDo {
	return d.withDO(d.DO.Session(config))
}

func (d defConditionDo) Clauses(conds ...clause.Expression) IDefConditionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d defConditionDo) Returning(value interface{}, columns ...string) IDefConditionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d defConditionDo) Not(conds ...gen.Condition) IDefConditionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d defConditionDo) Or(conds ...gen.Condition) IDefConditionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d defConditionDo) Select(conds ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d defConditionDo) Where(conds ...gen.Condition) IDefConditionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d defConditionDo) Order(conds ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d defConditionDo) Distinct(cols ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d defConditionDo) Omit(cols ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d defConditionDo) Join(table schema.Tabler, on ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d defConditionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d defConditionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d defConditionDo) Group(cols ...field.Expr) IDefConditionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d defConditionDo) Having(conds ...gen.Condition) IDefConditionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d defConditionDo) Limit(limit int) IDefConditionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d defConditionDo) Offset(offset int) IDefConditionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d defConditionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDefConditionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d defConditionDo) Unscoped() IDefConditionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d defConditionDo) Create(values ...*model.DefCondition) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d defConditionDo) CreateInBatches(values []*model.DefCondition, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d defConditionDo) Save(values ...*model.DefCondition) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d defConditionDo) First() (*model.DefCondition, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefCondition), nil
	}
}

func (d defConditionDo) Take() (*model.DefCondition, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefCondition), nil
	}
}

func (d defConditionDo) Last() (*model.DefCondition, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefCondition), nil
	}
}

func (d defConditionDo) Find() ([]*model.DefCondition, error) {
	result, err := d.DO.Find()
	return result.([]*model.DefCondition), err
}

func (d defConditionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DefCondition, err error) {
	buf := make([]*model.DefCondition, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d defConditionDo) FindInBatches(result *[]*model.DefCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d defConditionDo) Attrs(attrs ...field.AssignExpr) IDefConditionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d defConditionDo) Assign(attrs ...field.AssignExpr) IDefConditionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d defConditionDo) Joins(fields ...field.RelationField) IDefConditionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d defConditionDo) Preload(fields ...field.RelationField) IDefConditionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d defConditionDo) FirstOrInit() (*model.DefCondition, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefCondition), nil
	}
}

func (d defConditionDo) FirstOrCreate() (*model.DefCondition, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DefCondition), nil
	}
}

func (d defConditionDo) FindByPage(offset int, limit int) (result []*model.DefCondition, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d defConditionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d defConditionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d defConditionDo) Delete(models ...*model.DefCondition) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *defConditionDo) withDO(do gen.Dao) *defConditionDo {
	d.DO = *do.(*gen.DO)
	return d
}
