// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newLogAutomationExecution(db *gorm.DB, opts ...gen.DOOption) logAutomationExecution {
	_logAutomationExecution := logAutomationExecution{}

	_logAutomationExecution.logAutomationExecutionDo.UseDB(db, opts...)
	_logAutomationExecution.logAutomationExecutionDo.UseModel(&model.LogAutomationExecution{})

	tableName := _logAutomationExecution.logAutomationExecutionDo.TableName()
	_logAutomationExecution.ALL = field.NewAsterisk(tableName)
	_logAutomationExecution.LogID = field.NewString(tableName, "log_id")
	_logAutomationExecution.AutomationID = field.NewString(tableName, "automation_id")
	_logAutomationExecution.Status = field.NewString(tableName, "status")
	_logAutomationExecution.TriggeredAt = field.NewTime(tableName, "triggered_at")
	_logAutomationExecution.FinishedAt = field.NewTime(tableName, "finished_at")
	_logAutomationExecution.ConfigSnapshot = field.NewString(tableName, "config_snapshot")
	_logAutomationExecution.ExecutionDetails = field.NewString(tableName, "execution_details")
	_logAutomationExecution.ErrorMessage = field.NewString(tableName, "error_message")

	_logAutomationExecution.fillFieldMap()

	return _logAutomationExecution
}

type logAutomationExecution struct {
	logAutomationExecutionDo logAutomationExecutionDo

	ALL              field.Asterisk
	LogID            field.String
	AutomationID     field.String
	Status           field.String
	TriggeredAt      field.Time
	FinishedAt       field.Time
	ConfigSnapshot   field.String
	ExecutionDetails field.String
	ErrorMessage     field.String

	fieldMap map[string]field.Expr
}

func (l logAutomationExecution) Table(newTableName string) *logAutomationExecution {
	l.logAutomationExecutionDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l logAutomationExecution) As(alias string) *logAutomationExecution {
	l.logAutomationExecutionDo.DO = *(l.logAutomationExecutionDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *logAutomationExecution) updateTableName(table string) *logAutomationExecution {
	l.ALL = field.NewAsterisk(table)
	l.LogID = field.NewString(table, "log_id")
	l.AutomationID = field.NewString(table, "automation_id")
	l.Status = field.NewString(table, "status")
	l.TriggeredAt = field.NewTime(table, "triggered_at")
	l.FinishedAt = field.NewTime(table, "finished_at")
	l.ConfigSnapshot = field.NewString(table, "config_snapshot")
	l.ExecutionDetails = field.NewString(table, "execution_details")
	l.ErrorMessage = field.NewString(table, "error_message")

	l.fillFieldMap()

	return l
}

func (l *logAutomationExecution) WithContext(ctx context.Context) ILogAutomationExecutionDo {
	return l.logAutomationExecutionDo.WithContext(ctx)
}

func (l logAutomationExecution) TableName() string { return l.logAutomationExecutionDo.TableName() }

func (l logAutomationExecution) Alias() string { return l.logAutomationExecutionDo.Alias() }

func (l logAutomationExecution) Columns(cols ...field.Expr) gen.Columns {
	return l.logAutomationExecutionDo.Columns(cols...)
}

func (l *logAutomationExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *logAutomationExecution) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 8)
	l.fieldMap["log_id"] = l.LogID
	l.fieldMap["automation_id"] = l.AutomationID
	l.fieldMap["status"] = l.Status
	l.fieldMap["triggered_at"] = l.TriggeredAt
	l.fieldMap["finished_at"] = l.FinishedAt
	l.fieldMap["config_snapshot"] = l.ConfigSnapshot
	l.fieldMap["execution_details"] = l.ExecutionDetails
	l.fieldMap["error_message"] = l.ErrorMessage
}

func (l logAutomationExecution) clone(db *gorm.DB) logAutomationExecution {
	l.logAutomationExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l logAutomationExecution) replaceDB(db *gorm.DB) logAutomationExecution {
	l.logAutomationExecutionDo.ReplaceDB(db)
	return l
}

type logAutomationExecutionDo struct{ gen.DO }

type ILogAutomationExecutionDo interface {
	gen.SubQuery
	Debug() ILogAutomationExecutionDo
	WithContext(ctx context.Context) ILogAutomationExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILogAutomationExecutionDo
	WriteDB() ILogAutomationExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILogAutomationExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILogAutomationExecutionDo
	Not(conds ...gen.Condition) ILogAutomationExecutionDo
	Or(conds ...gen.Condition) ILogAutomationExecutionDo
	Select(conds ...field.Expr) ILogAutomationExecutionDo
	Where(conds ...gen.Condition) ILogAutomationExecutionDo
	Order(conds ...field.Expr) ILogAutomationExecutionDo
	Distinct(cols ...field.Expr) ILogAutomationExecutionDo
	Omit(cols ...field.Expr) ILogAutomationExecutionDo
	Join(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo
	Group(cols ...field.Expr) ILogAutomationExecutionDo
	Having(conds ...gen.Condition) ILogAutomationExecutionDo
	Limit(limit int) ILogAutomationExecutionDo
	Offset(offset int) ILogAutomationExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILogAutomationExecutionDo
	Unscoped() ILogAutomationExecutionDo
	Create(values ...*model.LogAutomationExecution) error
	CreateInBatches(values []*model.LogAutomationExecution, batchSize int) error
	Save(values ...*model.LogAutomationExecution) error
	First() (*model.LogAutomationExecution, error)
	Take() (*model.LogAutomationExecution, error)
	Last() (*model.LogAutomationExecution, error)
	Find() ([]*model.LogAutomationExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogAutomationExecution, err error)
	FindInBatches(result *[]*model.LogAutomationExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LogAutomationExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILogAutomationExecutionDo
	Assign(attrs ...field.AssignExpr) ILogAutomationExecutionDo
	Joins(fields ...field.RelationField) ILogAutomationExecutionDo
	Preload(fields ...field.RelationField) ILogAutomationExecutionDo
	FirstOrInit() (*model.LogAutomationExecution, error)
	FirstOrCreate() (*model.LogAutomationExecution, error)
	FindByPage(offset int, limit int) (result []*model.LogAutomationExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILogAutomationExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l logAutomationExecutionDo) Debug() ILogAutomationExecutionDo {
	return l.withDO(l.DO.Debug())
}

func (l logAutomationExecutionDo) WithContext(ctx context.Context) ILogAutomationExecutionDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l logAutomationExecutionDo) ReadDB() ILogAutomationExecutionDo {
	return l.Clauses(dbresolver.Read)
}

func (l logAutomationExecutionDo) WriteDB() ILogAutomationExecutionDo {
	return l.Clauses(dbresolver.Write)
}

func (l logAutomationExecutionDo) Session(config *gorm.Session) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Session(config))
}

func (l logAutomationExecutionDo) Clauses(conds ...clause.Expression) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l logAutomationExecutionDo) Returning(value interface{}, columns ...string) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l logAutomationExecutionDo) Not(conds ...gen.Condition) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l logAutomationExecutionDo) Or(conds ...gen.Condition) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l logAutomationExecutionDo) Select(conds ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l logAutomationExecutionDo) Where(conds ...gen.Condition) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l logAutomationExecutionDo) Order(conds ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l logAutomationExecutionDo) Distinct(cols ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l logAutomationExecutionDo) Omit(cols ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l logAutomationExecutionDo) Join(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l logAutomationExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l logAutomationExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l logAutomationExecutionDo) Group(cols ...field.Expr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l logAutomationExecutionDo) Having(conds ...gen.Condition) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l logAutomationExecutionDo) Limit(limit int) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l logAutomationExecutionDo) Offset(offset int) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l logAutomationExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l logAutomationExecutionDo) Unscoped() ILogAutomationExecutionDo {
	return l.withDO(l.DO.Unscoped())
}

func (l logAutomationExecutionDo) Create(values ...*model.LogAutomationExecution) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l logAutomationExecutionDo) CreateInBatches(values []*model.LogAutomationExecution, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l logAutomationExecutionDo) Save(values ...*model.LogAutomationExecution) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l logAutomationExecutionDo) First() (*model.LogAutomationExecution, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogAutomationExecution), nil
	}
}

func (l logAutomationExecutionDo) Take() (*model.LogAutomationExecution, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogAutomationExecution), nil
	}
}

func (l logAutomationExecutionDo) Last() (*model.LogAutomationExecution, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogAutomationExecution), nil
	}
}

func (l logAutomationExecutionDo) Find() ([]*model.LogAutomationExecution, error) {
	result, err := l.DO.Find()
	return result.([]*model.LogAutomationExecution), err
}

func (l logAutomationExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogAutomationExecution, err error) {
	buf := make([]*model.LogAutomationExecution, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l logAutomationExecutionDo) FindInBatches(result *[]*model.LogAutomationExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l logAutomationExecutionDo) Attrs(attrs ...field.AssignExpr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l logAutomationExecutionDo) Assign(attrs ...field.AssignExpr) ILogAutomationExecutionDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l logAutomationExecutionDo) Joins(fields ...field.RelationField) ILogAutomationExecutionDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l logAutomationExecutionDo) Preload(fields ...field.RelationField) ILogAutomationExecutionDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l logAutomationExecutionDo) FirstOrInit() (*model.LogAutomationExecution, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogAutomationExecution), nil
	}
}

func (l logAutomationExecutionDo) FirstOrCreate() (*model.LogAutomationExecution, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogAutomationExecution), nil
	}
}

func (l logAutomationExecutionDo) FindByPage(offset int, limit int) (result []*model.LogAutomationExecution, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l logAutomationExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l logAutomationExecutionDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l logAutomationExecutionDo) Delete(models ...*model.LogAutomationExecution) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *logAutomationExecutionDo) withDO(do gen.Dao) *logAutomationExecutionDo {
	l.DO = *do.(*gen.DO)
	return l
}
