// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newPolicyGroupAction(db *gorm.DB, opts ...gen.DOOption) policyGroupAction {
	_policyGroupAction := policyGroupAction{}

	_policyGroupAction.policyGroupActionDo.UseDB(db, opts...)
	_policyGroupAction.policyGroupActionDo.UseModel(&model.PolicyGroupAction{})

	tableName := _policyGroupAction.policyGroupActionDo.TableName()
	_policyGroupAction.ALL = field.NewAsterisk(tableName)
	_policyGroupAction.GroupID = field.NewString(tableName, "group_id")
	_policyGroupAction.ActionID = field.NewString(tableName, "action_id")
	_policyGroupAction.Created = field.NewTime(tableName, "created")
	_policyGroupAction.CreatedBy = field.NewString(tableName, "created_by")

	_policyGroupAction.fillFieldMap()

	return _policyGroupAction
}

type policyGroupAction struct {
	policyGroupActionDo policyGroupActionDo

	ALL       field.Asterisk
	GroupID   field.String
	ActionID  field.String
	Created   field.Time
	CreatedBy field.String

	fieldMap map[string]field.Expr
}

func (p policyGroupAction) Table(newTableName string) *policyGroupAction {
	p.policyGroupActionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyGroupAction) As(alias string) *policyGroupAction {
	p.policyGroupActionDo.DO = *(p.policyGroupActionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyGroupAction) updateTableName(table string) *policyGroupAction {
	p.ALL = field.NewAsterisk(table)
	p.GroupID = field.NewString(table, "group_id")
	p.ActionID = field.NewString(table, "action_id")
	p.Created = field.NewTime(table, "created")
	p.CreatedBy = field.NewString(table, "created_by")

	p.fillFieldMap()

	return p
}

func (p *policyGroupAction) WithContext(ctx context.Context) IPolicyGroupActionDo {
	return p.policyGroupActionDo.WithContext(ctx)
}

func (p policyGroupAction) TableName() string { return p.policyGroupActionDo.TableName() }

func (p policyGroupAction) Alias() string { return p.policyGroupActionDo.Alias() }

func (p policyGroupAction) Columns(cols ...field.Expr) gen.Columns {
	return p.policyGroupActionDo.Columns(cols...)
}

func (p *policyGroupAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyGroupAction) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["group_id"] = p.GroupID
	p.fieldMap["action_id"] = p.ActionID
	p.fieldMap["created"] = p.Created
	p.fieldMap["created_by"] = p.CreatedBy
}

func (p policyGroupAction) clone(db *gorm.DB) policyGroupAction {
	p.policyGroupActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyGroupAction) replaceDB(db *gorm.DB) policyGroupAction {
	p.policyGroupActionDo.ReplaceDB(db)
	return p
}

type policyGroupActionDo struct{ gen.DO }

type IPolicyGroupActionDo interface {
	gen.SubQuery
	Debug() IPolicyGroupActionDo
	WithContext(ctx context.Context) IPolicyGroupActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPolicyGroupActionDo
	WriteDB() IPolicyGroupActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPolicyGroupActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPolicyGroupActionDo
	Not(conds ...gen.Condition) IPolicyGroupActionDo
	Or(conds ...gen.Condition) IPolicyGroupActionDo
	Select(conds ...field.Expr) IPolicyGroupActionDo
	Where(conds ...gen.Condition) IPolicyGroupActionDo
	Order(conds ...field.Expr) IPolicyGroupActionDo
	Distinct(cols ...field.Expr) IPolicyGroupActionDo
	Omit(cols ...field.Expr) IPolicyGroupActionDo
	Join(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo
	Group(cols ...field.Expr) IPolicyGroupActionDo
	Having(conds ...gen.Condition) IPolicyGroupActionDo
	Limit(limit int) IPolicyGroupActionDo
	Offset(offset int) IPolicyGroupActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyGroupActionDo
	Unscoped() IPolicyGroupActionDo
	Create(values ...*model.PolicyGroupAction) error
	CreateInBatches(values []*model.PolicyGroupAction, batchSize int) error
	Save(values ...*model.PolicyGroupAction) error
	First() (*model.PolicyGroupAction, error)
	Take() (*model.PolicyGroupAction, error)
	Last() (*model.PolicyGroupAction, error)
	Find() ([]*model.PolicyGroupAction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyGroupAction, err error)
	FindInBatches(result *[]*model.PolicyGroupAction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PolicyGroupAction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPolicyGroupActionDo
	Assign(attrs ...field.AssignExpr) IPolicyGroupActionDo
	Joins(fields ...field.RelationField) IPolicyGroupActionDo
	Preload(fields ...field.RelationField) IPolicyGroupActionDo
	FirstOrInit() (*model.PolicyGroupAction, error)
	FirstOrCreate() (*model.PolicyGroupAction, error)
	FindByPage(offset int, limit int) (result []*model.PolicyGroupAction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPolicyGroupActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p policyGroupActionDo) Debug() IPolicyGroupActionDo {
	return p.withDO(p.DO.Debug())
}

func (p policyGroupActionDo) WithContext(ctx context.Context) IPolicyGroupActionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyGroupActionDo) ReadDB() IPolicyGroupActionDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyGroupActionDo) WriteDB() IPolicyGroupActionDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyGroupActionDo) Session(config *gorm.Session) IPolicyGroupActionDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyGroupActionDo) Clauses(conds ...clause.Expression) IPolicyGroupActionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyGroupActionDo) Returning(value interface{}, columns ...string) IPolicyGroupActionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyGroupActionDo) Not(conds ...gen.Condition) IPolicyGroupActionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyGroupActionDo) Or(conds ...gen.Condition) IPolicyGroupActionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyGroupActionDo) Select(conds ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyGroupActionDo) Where(conds ...gen.Condition) IPolicyGroupActionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyGroupActionDo) Order(conds ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyGroupActionDo) Distinct(cols ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyGroupActionDo) Omit(cols ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyGroupActionDo) Join(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyGroupActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyGroupActionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyGroupActionDo) Group(cols ...field.Expr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyGroupActionDo) Having(conds ...gen.Condition) IPolicyGroupActionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyGroupActionDo) Limit(limit int) IPolicyGroupActionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyGroupActionDo) Offset(offset int) IPolicyGroupActionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyGroupActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyGroupActionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyGroupActionDo) Unscoped() IPolicyGroupActionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyGroupActionDo) Create(values ...*model.PolicyGroupAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyGroupActionDo) CreateInBatches(values []*model.PolicyGroupAction, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyGroupActionDo) Save(values ...*model.PolicyGroupAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyGroupActionDo) First() (*model.PolicyGroupAction, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupAction), nil
	}
}

func (p policyGroupActionDo) Take() (*model.PolicyGroupAction, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupAction), nil
	}
}

func (p policyGroupActionDo) Last() (*model.PolicyGroupAction, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupAction), nil
	}
}

func (p policyGroupActionDo) Find() ([]*model.PolicyGroupAction, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyGroupAction), err
}

func (p policyGroupActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyGroupAction, err error) {
	buf := make([]*model.PolicyGroupAction, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyGroupActionDo) FindInBatches(result *[]*model.PolicyGroupAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyGroupActionDo) Attrs(attrs ...field.AssignExpr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyGroupActionDo) Assign(attrs ...field.AssignExpr) IPolicyGroupActionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyGroupActionDo) Joins(fields ...field.RelationField) IPolicyGroupActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyGroupActionDo) Preload(fields ...field.RelationField) IPolicyGroupActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyGroupActionDo) FirstOrInit() (*model.PolicyGroupAction, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupAction), nil
	}
}

func (p policyGroupActionDo) FirstOrCreate() (*model.PolicyGroupAction, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupAction), nil
	}
}

func (p policyGroupActionDo) FindByPage(offset int, limit int) (result []*model.PolicyGroupAction, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyGroupActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyGroupActionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyGroupActionDo) Delete(models ...*model.PolicyGroupAction) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyGroupActionDo) withDO(do gen.Dao) *policyGroupActionDo {
	p.DO = *do.(*gen.DO)
	return p
}
