// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newPolicyConditionAction(db *gorm.DB, opts ...gen.DOOption) policyConditionAction {
	_policyConditionAction := policyConditionAction{}

	_policyConditionAction.policyConditionActionDo.UseDB(db, opts...)
	_policyConditionAction.policyConditionActionDo.UseModel(&model.PolicyConditionAction{})

	tableName := _policyConditionAction.policyConditionActionDo.TableName()
	_policyConditionAction.ALL = field.NewAsterisk(tableName)
	_policyConditionAction.MyRowID = field.NewInt64(tableName, "my_row_id")
	_policyConditionAction.ConditionID = field.NewString(tableName, "condition_id")
	_policyConditionAction.ActionID = field.NewString(tableName, "action_id")
	_policyConditionAction.Created = field.NewTime(tableName, "created")
	_policyConditionAction.CreatedBy = field.NewString(tableName, "created_by")

	_policyConditionAction.fillFieldMap()

	return _policyConditionAction
}

type policyConditionAction struct {
	policyConditionActionDo policyConditionActionDo

	ALL         field.Asterisk
	MyRowID     field.Int64
	ConditionID field.String
	ActionID    field.String
	Created     field.Time
	CreatedBy   field.String

	fieldMap map[string]field.Expr
}

func (p policyConditionAction) Table(newTableName string) *policyConditionAction {
	p.policyConditionActionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyConditionAction) As(alias string) *policyConditionAction {
	p.policyConditionActionDo.DO = *(p.policyConditionActionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyConditionAction) updateTableName(table string) *policyConditionAction {
	p.ALL = field.NewAsterisk(table)
	p.MyRowID = field.NewInt64(table, "my_row_id")
	p.ConditionID = field.NewString(table, "condition_id")
	p.ActionID = field.NewString(table, "action_id")
	p.Created = field.NewTime(table, "created")
	p.CreatedBy = field.NewString(table, "created_by")

	p.fillFieldMap()

	return p
}

func (p *policyConditionAction) WithContext(ctx context.Context) IPolicyConditionActionDo {
	return p.policyConditionActionDo.WithContext(ctx)
}

func (p policyConditionAction) TableName() string { return p.policyConditionActionDo.TableName() }

func (p policyConditionAction) Alias() string { return p.policyConditionActionDo.Alias() }

func (p policyConditionAction) Columns(cols ...field.Expr) gen.Columns {
	return p.policyConditionActionDo.Columns(cols...)
}

func (p *policyConditionAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyConditionAction) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["my_row_id"] = p.MyRowID
	p.fieldMap["condition_id"] = p.ConditionID
	p.fieldMap["action_id"] = p.ActionID
	p.fieldMap["created"] = p.Created
	p.fieldMap["created_by"] = p.CreatedBy
}

func (p policyConditionAction) clone(db *gorm.DB) policyConditionAction {
	p.policyConditionActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyConditionAction) replaceDB(db *gorm.DB) policyConditionAction {
	p.policyConditionActionDo.ReplaceDB(db)
	return p
}

type policyConditionActionDo struct{ gen.DO }

type IPolicyConditionActionDo interface {
	gen.SubQuery
	Debug() IPolicyConditionActionDo
	WithContext(ctx context.Context) IPolicyConditionActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPolicyConditionActionDo
	WriteDB() IPolicyConditionActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPolicyConditionActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPolicyConditionActionDo
	Not(conds ...gen.Condition) IPolicyConditionActionDo
	Or(conds ...gen.Condition) IPolicyConditionActionDo
	Select(conds ...field.Expr) IPolicyConditionActionDo
	Where(conds ...gen.Condition) IPolicyConditionActionDo
	Order(conds ...field.Expr) IPolicyConditionActionDo
	Distinct(cols ...field.Expr) IPolicyConditionActionDo
	Omit(cols ...field.Expr) IPolicyConditionActionDo
	Join(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo
	Group(cols ...field.Expr) IPolicyConditionActionDo
	Having(conds ...gen.Condition) IPolicyConditionActionDo
	Limit(limit int) IPolicyConditionActionDo
	Offset(offset int) IPolicyConditionActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyConditionActionDo
	Unscoped() IPolicyConditionActionDo
	Create(values ...*model.PolicyConditionAction) error
	CreateInBatches(values []*model.PolicyConditionAction, batchSize int) error
	Save(values ...*model.PolicyConditionAction) error
	First() (*model.PolicyConditionAction, error)
	Take() (*model.PolicyConditionAction, error)
	Last() (*model.PolicyConditionAction, error)
	Find() ([]*model.PolicyConditionAction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyConditionAction, err error)
	FindInBatches(result *[]*model.PolicyConditionAction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PolicyConditionAction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPolicyConditionActionDo
	Assign(attrs ...field.AssignExpr) IPolicyConditionActionDo
	Joins(fields ...field.RelationField) IPolicyConditionActionDo
	Preload(fields ...field.RelationField) IPolicyConditionActionDo
	FirstOrInit() (*model.PolicyConditionAction, error)
	FirstOrCreate() (*model.PolicyConditionAction, error)
	FindByPage(offset int, limit int) (result []*model.PolicyConditionAction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPolicyConditionActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p policyConditionActionDo) Debug() IPolicyConditionActionDo {
	return p.withDO(p.DO.Debug())
}

func (p policyConditionActionDo) WithContext(ctx context.Context) IPolicyConditionActionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyConditionActionDo) ReadDB() IPolicyConditionActionDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyConditionActionDo) WriteDB() IPolicyConditionActionDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyConditionActionDo) Session(config *gorm.Session) IPolicyConditionActionDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyConditionActionDo) Clauses(conds ...clause.Expression) IPolicyConditionActionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyConditionActionDo) Returning(value interface{}, columns ...string) IPolicyConditionActionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyConditionActionDo) Not(conds ...gen.Condition) IPolicyConditionActionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyConditionActionDo) Or(conds ...gen.Condition) IPolicyConditionActionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyConditionActionDo) Select(conds ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyConditionActionDo) Where(conds ...gen.Condition) IPolicyConditionActionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyConditionActionDo) Order(conds ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyConditionActionDo) Distinct(cols ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyConditionActionDo) Omit(cols ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyConditionActionDo) Join(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyConditionActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyConditionActionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyConditionActionDo) Group(cols ...field.Expr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyConditionActionDo) Having(conds ...gen.Condition) IPolicyConditionActionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyConditionActionDo) Limit(limit int) IPolicyConditionActionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyConditionActionDo) Offset(offset int) IPolicyConditionActionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyConditionActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyConditionActionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyConditionActionDo) Unscoped() IPolicyConditionActionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyConditionActionDo) Create(values ...*model.PolicyConditionAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyConditionActionDo) CreateInBatches(values []*model.PolicyConditionAction, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyConditionActionDo) Save(values ...*model.PolicyConditionAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyConditionActionDo) First() (*model.PolicyConditionAction, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionAction), nil
	}
}

func (p policyConditionActionDo) Take() (*model.PolicyConditionAction, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionAction), nil
	}
}

func (p policyConditionActionDo) Last() (*model.PolicyConditionAction, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionAction), nil
	}
}

func (p policyConditionActionDo) Find() ([]*model.PolicyConditionAction, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyConditionAction), err
}

func (p policyConditionActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyConditionAction, err error) {
	buf := make([]*model.PolicyConditionAction, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyConditionActionDo) FindInBatches(result *[]*model.PolicyConditionAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyConditionActionDo) Attrs(attrs ...field.AssignExpr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyConditionActionDo) Assign(attrs ...field.AssignExpr) IPolicyConditionActionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyConditionActionDo) Joins(fields ...field.RelationField) IPolicyConditionActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyConditionActionDo) Preload(fields ...field.RelationField) IPolicyConditionActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyConditionActionDo) FirstOrInit() (*model.PolicyConditionAction, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionAction), nil
	}
}

func (p policyConditionActionDo) FirstOrCreate() (*model.PolicyConditionAction, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionAction), nil
	}
}

func (p policyConditionActionDo) FindByPage(offset int, limit int) (result []*model.PolicyConditionAction, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyConditionActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyConditionActionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyConditionActionDo) Delete(models ...*model.PolicyConditionAction) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyConditionActionDo) withDO(do gen.Dao) *policyConditionActionDo {
	p.DO = *do.(*gen.DO)
	return p
}
