// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newPolicyConditionUnit(db *gorm.DB, opts ...gen.DOOption) policyConditionUnit {
	_policyConditionUnit := policyConditionUnit{}

	_policyConditionUnit.policyConditionUnitDo.UseDB(db, opts...)
	_policyConditionUnit.policyConditionUnitDo.UseModel(&model.PolicyConditionUnit{})

	tableName := _policyConditionUnit.policyConditionUnitDo.TableName()
	_policyConditionUnit.ALL = field.NewAsterisk(tableName)
	_policyConditionUnit.ConditionID = field.NewString(tableName, "condition_id")
	_policyConditionUnit.UnitID = field.NewString(tableName, "unit_id")
	_policyConditionUnit.Created = field.NewTime(tableName, "created")
	_policyConditionUnit.CreatedBy = field.NewString(tableName, "created_by")

	_policyConditionUnit.fillFieldMap()

	return _policyConditionUnit
}

type policyConditionUnit struct {
	policyConditionUnitDo policyConditionUnitDo

	ALL         field.Asterisk
	ConditionID field.String
	UnitID      field.String
	Created     field.Time
	CreatedBy   field.String

	fieldMap map[string]field.Expr
}

func (p policyConditionUnit) Table(newTableName string) *policyConditionUnit {
	p.policyConditionUnitDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyConditionUnit) As(alias string) *policyConditionUnit {
	p.policyConditionUnitDo.DO = *(p.policyConditionUnitDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyConditionUnit) updateTableName(table string) *policyConditionUnit {
	p.ALL = field.NewAsterisk(table)
	p.ConditionID = field.NewString(table, "condition_id")
	p.UnitID = field.NewString(table, "unit_id")
	p.Created = field.NewTime(table, "created")
	p.CreatedBy = field.NewString(table, "created_by")

	p.fillFieldMap()

	return p
}

func (p *policyConditionUnit) WithContext(ctx context.Context) IPolicyConditionUnitDo {
	return p.policyConditionUnitDo.WithContext(ctx)
}

func (p policyConditionUnit) TableName() string { return p.policyConditionUnitDo.TableName() }

func (p policyConditionUnit) Alias() string { return p.policyConditionUnitDo.Alias() }

func (p policyConditionUnit) Columns(cols ...field.Expr) gen.Columns {
	return p.policyConditionUnitDo.Columns(cols...)
}

func (p *policyConditionUnit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyConditionUnit) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["condition_id"] = p.ConditionID
	p.fieldMap["unit_id"] = p.UnitID
	p.fieldMap["created"] = p.Created
	p.fieldMap["created_by"] = p.CreatedBy
}

func (p policyConditionUnit) clone(db *gorm.DB) policyConditionUnit {
	p.policyConditionUnitDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyConditionUnit) replaceDB(db *gorm.DB) policyConditionUnit {
	p.policyConditionUnitDo.ReplaceDB(db)
	return p
}

type policyConditionUnitDo struct{ gen.DO }

type IPolicyConditionUnitDo interface {
	gen.SubQuery
	Debug() IPolicyConditionUnitDo
	WithContext(ctx context.Context) IPolicyConditionUnitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPolicyConditionUnitDo
	WriteDB() IPolicyConditionUnitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPolicyConditionUnitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPolicyConditionUnitDo
	Not(conds ...gen.Condition) IPolicyConditionUnitDo
	Or(conds ...gen.Condition) IPolicyConditionUnitDo
	Select(conds ...field.Expr) IPolicyConditionUnitDo
	Where(conds ...gen.Condition) IPolicyConditionUnitDo
	Order(conds ...field.Expr) IPolicyConditionUnitDo
	Distinct(cols ...field.Expr) IPolicyConditionUnitDo
	Omit(cols ...field.Expr) IPolicyConditionUnitDo
	Join(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo
	Group(cols ...field.Expr) IPolicyConditionUnitDo
	Having(conds ...gen.Condition) IPolicyConditionUnitDo
	Limit(limit int) IPolicyConditionUnitDo
	Offset(offset int) IPolicyConditionUnitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyConditionUnitDo
	Unscoped() IPolicyConditionUnitDo
	Create(values ...*model.PolicyConditionUnit) error
	CreateInBatches(values []*model.PolicyConditionUnit, batchSize int) error
	Save(values ...*model.PolicyConditionUnit) error
	First() (*model.PolicyConditionUnit, error)
	Take() (*model.PolicyConditionUnit, error)
	Last() (*model.PolicyConditionUnit, error)
	Find() ([]*model.PolicyConditionUnit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyConditionUnit, err error)
	FindInBatches(result *[]*model.PolicyConditionUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PolicyConditionUnit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPolicyConditionUnitDo
	Assign(attrs ...field.AssignExpr) IPolicyConditionUnitDo
	Joins(fields ...field.RelationField) IPolicyConditionUnitDo
	Preload(fields ...field.RelationField) IPolicyConditionUnitDo
	FirstOrInit() (*model.PolicyConditionUnit, error)
	FirstOrCreate() (*model.PolicyConditionUnit, error)
	FindByPage(offset int, limit int) (result []*model.PolicyConditionUnit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPolicyConditionUnitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p policyConditionUnitDo) Debug() IPolicyConditionUnitDo {
	return p.withDO(p.DO.Debug())
}

func (p policyConditionUnitDo) WithContext(ctx context.Context) IPolicyConditionUnitDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyConditionUnitDo) ReadDB() IPolicyConditionUnitDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyConditionUnitDo) WriteDB() IPolicyConditionUnitDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyConditionUnitDo) Session(config *gorm.Session) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyConditionUnitDo) Clauses(conds ...clause.Expression) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyConditionUnitDo) Returning(value interface{}, columns ...string) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyConditionUnitDo) Not(conds ...gen.Condition) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyConditionUnitDo) Or(conds ...gen.Condition) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyConditionUnitDo) Select(conds ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyConditionUnitDo) Where(conds ...gen.Condition) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyConditionUnitDo) Order(conds ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyConditionUnitDo) Distinct(cols ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyConditionUnitDo) Omit(cols ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyConditionUnitDo) Join(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyConditionUnitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyConditionUnitDo) RightJoin(table schema.Tabler, on ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyConditionUnitDo) Group(cols ...field.Expr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyConditionUnitDo) Having(conds ...gen.Condition) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyConditionUnitDo) Limit(limit int) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyConditionUnitDo) Offset(offset int) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyConditionUnitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyConditionUnitDo) Unscoped() IPolicyConditionUnitDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyConditionUnitDo) Create(values ...*model.PolicyConditionUnit) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyConditionUnitDo) CreateInBatches(values []*model.PolicyConditionUnit, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyConditionUnitDo) Save(values ...*model.PolicyConditionUnit) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyConditionUnitDo) First() (*model.PolicyConditionUnit, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionUnit), nil
	}
}

func (p policyConditionUnitDo) Take() (*model.PolicyConditionUnit, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionUnit), nil
	}
}

func (p policyConditionUnitDo) Last() (*model.PolicyConditionUnit, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionUnit), nil
	}
}

func (p policyConditionUnitDo) Find() ([]*model.PolicyConditionUnit, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyConditionUnit), err
}

func (p policyConditionUnitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyConditionUnit, err error) {
	buf := make([]*model.PolicyConditionUnit, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyConditionUnitDo) FindInBatches(result *[]*model.PolicyConditionUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyConditionUnitDo) Attrs(attrs ...field.AssignExpr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyConditionUnitDo) Assign(attrs ...field.AssignExpr) IPolicyConditionUnitDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyConditionUnitDo) Joins(fields ...field.RelationField) IPolicyConditionUnitDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyConditionUnitDo) Preload(fields ...field.RelationField) IPolicyConditionUnitDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyConditionUnitDo) FirstOrInit() (*model.PolicyConditionUnit, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionUnit), nil
	}
}

func (p policyConditionUnitDo) FirstOrCreate() (*model.PolicyConditionUnit, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyConditionUnit), nil
	}
}

func (p policyConditionUnitDo) FindByPage(offset int, limit int) (result []*model.PolicyConditionUnit, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyConditionUnitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyConditionUnitDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyConditionUnitDo) Delete(models ...*model.PolicyConditionUnit) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyConditionUnitDo) withDO(do gen.Dao) *policyConditionUnitDo {
	p.DO = *do.(*gen.DO)
	return p
}
