// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newPolicyGroupCondition(db *gorm.DB, opts ...gen.DOOption) policyGroupCondition {
	_policyGroupCondition := policyGroupCondition{}

	_policyGroupCondition.policyGroupConditionDo.UseDB(db, opts...)
	_policyGroupCondition.policyGroupConditionDo.UseModel(&model.PolicyGroupCondition{})

	tableName := _policyGroupCondition.policyGroupConditionDo.TableName()
	_policyGroupCondition.ALL = field.NewAsterisk(tableName)
	_policyGroupCondition.GroupID = field.NewString(tableName, "group_id")
	_policyGroupCondition.ConditionID = field.NewString(tableName, "condition_id")
	_policyGroupCondition.Created = field.NewTime(tableName, "created")
	_policyGroupCondition.CreatedBy = field.NewString(tableName, "created_by")

	_policyGroupCondition.fillFieldMap()

	return _policyGroupCondition
}

type policyGroupCondition struct {
	policyGroupConditionDo policyGroupConditionDo

	ALL         field.Asterisk
	GroupID     field.String
	ConditionID field.String
	Created     field.Time
	CreatedBy   field.String

	fieldMap map[string]field.Expr
}

func (p policyGroupCondition) Table(newTableName string) *policyGroupCondition {
	p.policyGroupConditionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyGroupCondition) As(alias string) *policyGroupCondition {
	p.policyGroupConditionDo.DO = *(p.policyGroupConditionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyGroupCondition) updateTableName(table string) *policyGroupCondition {
	p.ALL = field.NewAsterisk(table)
	p.GroupID = field.NewString(table, "group_id")
	p.ConditionID = field.NewString(table, "condition_id")
	p.Created = field.NewTime(table, "created")
	p.CreatedBy = field.NewString(table, "created_by")

	p.fillFieldMap()

	return p
}

func (p *policyGroupCondition) WithContext(ctx context.Context) IPolicyGroupConditionDo {
	return p.policyGroupConditionDo.WithContext(ctx)
}

func (p policyGroupCondition) TableName() string { return p.policyGroupConditionDo.TableName() }

func (p policyGroupCondition) Alias() string { return p.policyGroupConditionDo.Alias() }

func (p policyGroupCondition) Columns(cols ...field.Expr) gen.Columns {
	return p.policyGroupConditionDo.Columns(cols...)
}

func (p *policyGroupCondition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyGroupCondition) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["group_id"] = p.GroupID
	p.fieldMap["condition_id"] = p.ConditionID
	p.fieldMap["created"] = p.Created
	p.fieldMap["created_by"] = p.CreatedBy
}

func (p policyGroupCondition) clone(db *gorm.DB) policyGroupCondition {
	p.policyGroupConditionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyGroupCondition) replaceDB(db *gorm.DB) policyGroupCondition {
	p.policyGroupConditionDo.ReplaceDB(db)
	return p
}

type policyGroupConditionDo struct{ gen.DO }

type IPolicyGroupConditionDo interface {
	gen.SubQuery
	Debug() IPolicyGroupConditionDo
	WithContext(ctx context.Context) IPolicyGroupConditionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPolicyGroupConditionDo
	WriteDB() IPolicyGroupConditionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPolicyGroupConditionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPolicyGroupConditionDo
	Not(conds ...gen.Condition) IPolicyGroupConditionDo
	Or(conds ...gen.Condition) IPolicyGroupConditionDo
	Select(conds ...field.Expr) IPolicyGroupConditionDo
	Where(conds ...gen.Condition) IPolicyGroupConditionDo
	Order(conds ...field.Expr) IPolicyGroupConditionDo
	Distinct(cols ...field.Expr) IPolicyGroupConditionDo
	Omit(cols ...field.Expr) IPolicyGroupConditionDo
	Join(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo
	Group(cols ...field.Expr) IPolicyGroupConditionDo
	Having(conds ...gen.Condition) IPolicyGroupConditionDo
	Limit(limit int) IPolicyGroupConditionDo
	Offset(offset int) IPolicyGroupConditionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyGroupConditionDo
	Unscoped() IPolicyGroupConditionDo
	Create(values ...*model.PolicyGroupCondition) error
	CreateInBatches(values []*model.PolicyGroupCondition, batchSize int) error
	Save(values ...*model.PolicyGroupCondition) error
	First() (*model.PolicyGroupCondition, error)
	Take() (*model.PolicyGroupCondition, error)
	Last() (*model.PolicyGroupCondition, error)
	Find() ([]*model.PolicyGroupCondition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyGroupCondition, err error)
	FindInBatches(result *[]*model.PolicyGroupCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PolicyGroupCondition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPolicyGroupConditionDo
	Assign(attrs ...field.AssignExpr) IPolicyGroupConditionDo
	Joins(fields ...field.RelationField) IPolicyGroupConditionDo
	Preload(fields ...field.RelationField) IPolicyGroupConditionDo
	FirstOrInit() (*model.PolicyGroupCondition, error)
	FirstOrCreate() (*model.PolicyGroupCondition, error)
	FindByPage(offset int, limit int) (result []*model.PolicyGroupCondition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPolicyGroupConditionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p policyGroupConditionDo) Debug() IPolicyGroupConditionDo {
	return p.withDO(p.DO.Debug())
}

func (p policyGroupConditionDo) WithContext(ctx context.Context) IPolicyGroupConditionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyGroupConditionDo) ReadDB() IPolicyGroupConditionDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyGroupConditionDo) WriteDB() IPolicyGroupConditionDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyGroupConditionDo) Session(config *gorm.Session) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyGroupConditionDo) Clauses(conds ...clause.Expression) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyGroupConditionDo) Returning(value interface{}, columns ...string) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyGroupConditionDo) Not(conds ...gen.Condition) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyGroupConditionDo) Or(conds ...gen.Condition) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyGroupConditionDo) Select(conds ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyGroupConditionDo) Where(conds ...gen.Condition) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyGroupConditionDo) Order(conds ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyGroupConditionDo) Distinct(cols ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyGroupConditionDo) Omit(cols ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyGroupConditionDo) Join(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyGroupConditionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyGroupConditionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyGroupConditionDo) Group(cols ...field.Expr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyGroupConditionDo) Having(conds ...gen.Condition) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyGroupConditionDo) Limit(limit int) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyGroupConditionDo) Offset(offset int) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyGroupConditionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyGroupConditionDo) Unscoped() IPolicyGroupConditionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyGroupConditionDo) Create(values ...*model.PolicyGroupCondition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyGroupConditionDo) CreateInBatches(values []*model.PolicyGroupCondition, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyGroupConditionDo) Save(values ...*model.PolicyGroupCondition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyGroupConditionDo) First() (*model.PolicyGroupCondition, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupCondition), nil
	}
}

func (p policyGroupConditionDo) Take() (*model.PolicyGroupCondition, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupCondition), nil
	}
}

func (p policyGroupConditionDo) Last() (*model.PolicyGroupCondition, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupCondition), nil
	}
}

func (p policyGroupConditionDo) Find() ([]*model.PolicyGroupCondition, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyGroupCondition), err
}

func (p policyGroupConditionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyGroupCondition, err error) {
	buf := make([]*model.PolicyGroupCondition, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyGroupConditionDo) FindInBatches(result *[]*model.PolicyGroupCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyGroupConditionDo) Attrs(attrs ...field.AssignExpr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyGroupConditionDo) Assign(attrs ...field.AssignExpr) IPolicyGroupConditionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyGroupConditionDo) Joins(fields ...field.RelationField) IPolicyGroupConditionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyGroupConditionDo) Preload(fields ...field.RelationField) IPolicyGroupConditionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyGroupConditionDo) FirstOrInit() (*model.PolicyGroupCondition, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupCondition), nil
	}
}

func (p policyGroupConditionDo) FirstOrCreate() (*model.PolicyGroupCondition, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyGroupCondition), nil
	}
}

func (p policyGroupConditionDo) FindByPage(offset int, limit int) (result []*model.PolicyGroupCondition, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyGroupConditionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyGroupConditionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyGroupConditionDo) Delete(models ...*model.PolicyGroupCondition) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyGroupConditionDo) withDO(do gen.Dao) *policyGroupConditionDo {
	p.DO = *do.(*gen.DO)
	return p
}
