// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newRunAutomationConditionGroup(db *gorm.DB, opts ...gen.DOOption) runAutomationConditionGroup {
	_runAutomationConditionGroup := runAutomationConditionGroup{}

	_runAutomationConditionGroup.runAutomationConditionGroupDo.UseDB(db, opts...)
	_runAutomationConditionGroup.runAutomationConditionGroupDo.UseModel(&model.RunAutomationConditionGroup{})

	tableName := _runAutomationConditionGroup.runAutomationConditionGroupDo.TableName()
	_runAutomationConditionGroup.ALL = field.NewAsterisk(tableName)
	_runAutomationConditionGroup.AutomationConditionGroupID = field.NewString(tableName, "automation_condition_group_id")
	_runAutomationConditionGroup.AutomationID = field.NewString(tableName, "automation_id")
	_runAutomationConditionGroup.GroupOperator = field.NewString(tableName, "group_operator")
	_runAutomationConditionGroup.SortOrder = field.NewInt32(tableName, "sort_order")
	_runAutomationConditionGroup.Created = field.NewTime(tableName, "created")
	_runAutomationConditionGroup.CreatedBy = field.NewString(tableName, "created_by")
	_runAutomationConditionGroup.LastUpd = field.NewTime(tableName, "last_upd")
	_runAutomationConditionGroup.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_runAutomationConditionGroup.fillFieldMap()

	return _runAutomationConditionGroup
}

type runAutomationConditionGroup struct {
	runAutomationConditionGroupDo runAutomationConditionGroupDo

	ALL                        field.Asterisk
	AutomationConditionGroupID field.String
	AutomationID               field.String
	GroupOperator              field.String
	SortOrder                  field.Int32
	Created                    field.Time
	CreatedBy                  field.String
	LastUpd                    field.Time
	LastUpdBy                  field.String

	fieldMap map[string]field.Expr
}

func (r runAutomationConditionGroup) Table(newTableName string) *runAutomationConditionGroup {
	r.runAutomationConditionGroupDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runAutomationConditionGroup) As(alias string) *runAutomationConditionGroup {
	r.runAutomationConditionGroupDo.DO = *(r.runAutomationConditionGroupDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runAutomationConditionGroup) updateTableName(table string) *runAutomationConditionGroup {
	r.ALL = field.NewAsterisk(table)
	r.AutomationConditionGroupID = field.NewString(table, "automation_condition_group_id")
	r.AutomationID = field.NewString(table, "automation_id")
	r.GroupOperator = field.NewString(table, "group_operator")
	r.SortOrder = field.NewInt32(table, "sort_order")
	r.Created = field.NewTime(table, "created")
	r.CreatedBy = field.NewString(table, "created_by")
	r.LastUpd = field.NewTime(table, "last_upd")
	r.LastUpdBy = field.NewString(table, "last_upd_by")

	r.fillFieldMap()

	return r
}

func (r *runAutomationConditionGroup) WithContext(ctx context.Context) IRunAutomationConditionGroupDo {
	return r.runAutomationConditionGroupDo.WithContext(ctx)
}

func (r runAutomationConditionGroup) TableName() string {
	return r.runAutomationConditionGroupDo.TableName()
}

func (r runAutomationConditionGroup) Alias() string { return r.runAutomationConditionGroupDo.Alias() }

func (r runAutomationConditionGroup) Columns(cols ...field.Expr) gen.Columns {
	return r.runAutomationConditionGroupDo.Columns(cols...)
}

func (r *runAutomationConditionGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runAutomationConditionGroup) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["automation_condition_group_id"] = r.AutomationConditionGroupID
	r.fieldMap["automation_id"] = r.AutomationID
	r.fieldMap["group_operator"] = r.GroupOperator
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["created"] = r.Created
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["last_upd"] = r.LastUpd
	r.fieldMap["last_upd_by"] = r.LastUpdBy
}

func (r runAutomationConditionGroup) clone(db *gorm.DB) runAutomationConditionGroup {
	r.runAutomationConditionGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runAutomationConditionGroup) replaceDB(db *gorm.DB) runAutomationConditionGroup {
	r.runAutomationConditionGroupDo.ReplaceDB(db)
	return r
}

type runAutomationConditionGroupDo struct{ gen.DO }

type IRunAutomationConditionGroupDo interface {
	gen.SubQuery
	Debug() IRunAutomationConditionGroupDo
	WithContext(ctx context.Context) IRunAutomationConditionGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunAutomationConditionGroupDo
	WriteDB() IRunAutomationConditionGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunAutomationConditionGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunAutomationConditionGroupDo
	Not(conds ...gen.Condition) IRunAutomationConditionGroupDo
	Or(conds ...gen.Condition) IRunAutomationConditionGroupDo
	Select(conds ...field.Expr) IRunAutomationConditionGroupDo
	Where(conds ...gen.Condition) IRunAutomationConditionGroupDo
	Order(conds ...field.Expr) IRunAutomationConditionGroupDo
	Distinct(cols ...field.Expr) IRunAutomationConditionGroupDo
	Omit(cols ...field.Expr) IRunAutomationConditionGroupDo
	Join(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo
	Group(cols ...field.Expr) IRunAutomationConditionGroupDo
	Having(conds ...gen.Condition) IRunAutomationConditionGroupDo
	Limit(limit int) IRunAutomationConditionGroupDo
	Offset(offset int) IRunAutomationConditionGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationConditionGroupDo
	Unscoped() IRunAutomationConditionGroupDo
	Create(values ...*model.RunAutomationConditionGroup) error
	CreateInBatches(values []*model.RunAutomationConditionGroup, batchSize int) error
	Save(values ...*model.RunAutomationConditionGroup) error
	First() (*model.RunAutomationConditionGroup, error)
	Take() (*model.RunAutomationConditionGroup, error)
	Last() (*model.RunAutomationConditionGroup, error)
	Find() ([]*model.RunAutomationConditionGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationConditionGroup, err error)
	FindInBatches(result *[]*model.RunAutomationConditionGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunAutomationConditionGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunAutomationConditionGroupDo
	Assign(attrs ...field.AssignExpr) IRunAutomationConditionGroupDo
	Joins(fields ...field.RelationField) IRunAutomationConditionGroupDo
	Preload(fields ...field.RelationField) IRunAutomationConditionGroupDo
	FirstOrInit() (*model.RunAutomationConditionGroup, error)
	FirstOrCreate() (*model.RunAutomationConditionGroup, error)
	FindByPage(offset int, limit int) (result []*model.RunAutomationConditionGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunAutomationConditionGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runAutomationConditionGroupDo) Debug() IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Debug())
}

func (r runAutomationConditionGroupDo) WithContext(ctx context.Context) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runAutomationConditionGroupDo) ReadDB() IRunAutomationConditionGroupDo {
	return r.Clauses(dbresolver.Read)
}

func (r runAutomationConditionGroupDo) WriteDB() IRunAutomationConditionGroupDo {
	return r.Clauses(dbresolver.Write)
}

func (r runAutomationConditionGroupDo) Session(config *gorm.Session) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Session(config))
}

func (r runAutomationConditionGroupDo) Clauses(conds ...clause.Expression) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runAutomationConditionGroupDo) Returning(value interface{}, columns ...string) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runAutomationConditionGroupDo) Not(conds ...gen.Condition) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runAutomationConditionGroupDo) Or(conds ...gen.Condition) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runAutomationConditionGroupDo) Select(conds ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runAutomationConditionGroupDo) Where(conds ...gen.Condition) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runAutomationConditionGroupDo) Order(conds ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runAutomationConditionGroupDo) Distinct(cols ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runAutomationConditionGroupDo) Omit(cols ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runAutomationConditionGroupDo) Join(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runAutomationConditionGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runAutomationConditionGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runAutomationConditionGroupDo) Group(cols ...field.Expr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runAutomationConditionGroupDo) Having(conds ...gen.Condition) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runAutomationConditionGroupDo) Limit(limit int) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runAutomationConditionGroupDo) Offset(offset int) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runAutomationConditionGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runAutomationConditionGroupDo) Unscoped() IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runAutomationConditionGroupDo) Create(values ...*model.RunAutomationConditionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runAutomationConditionGroupDo) CreateInBatches(values []*model.RunAutomationConditionGroup, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runAutomationConditionGroupDo) Save(values ...*model.RunAutomationConditionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runAutomationConditionGroupDo) First() (*model.RunAutomationConditionGroup, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationConditionGroup), nil
	}
}

func (r runAutomationConditionGroupDo) Take() (*model.RunAutomationConditionGroup, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationConditionGroup), nil
	}
}

func (r runAutomationConditionGroupDo) Last() (*model.RunAutomationConditionGroup, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationConditionGroup), nil
	}
}

func (r runAutomationConditionGroupDo) Find() ([]*model.RunAutomationConditionGroup, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunAutomationConditionGroup), err
}

func (r runAutomationConditionGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationConditionGroup, err error) {
	buf := make([]*model.RunAutomationConditionGroup, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runAutomationConditionGroupDo) FindInBatches(result *[]*model.RunAutomationConditionGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runAutomationConditionGroupDo) Attrs(attrs ...field.AssignExpr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runAutomationConditionGroupDo) Assign(attrs ...field.AssignExpr) IRunAutomationConditionGroupDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runAutomationConditionGroupDo) Joins(fields ...field.RelationField) IRunAutomationConditionGroupDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runAutomationConditionGroupDo) Preload(fields ...field.RelationField) IRunAutomationConditionGroupDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runAutomationConditionGroupDo) FirstOrInit() (*model.RunAutomationConditionGroup, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationConditionGroup), nil
	}
}

func (r runAutomationConditionGroupDo) FirstOrCreate() (*model.RunAutomationConditionGroup, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationConditionGroup), nil
	}
}

func (r runAutomationConditionGroupDo) FindByPage(offset int, limit int) (result []*model.RunAutomationConditionGroup, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runAutomationConditionGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runAutomationConditionGroupDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runAutomationConditionGroupDo) Delete(models ...*model.RunAutomationConditionGroup) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runAutomationConditionGroupDo) withDO(do gen.Dao) *runAutomationConditionGroupDo {
	r.DO = *do.(*gen.DO)
	return r
}
