// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newRunAutomation(db *gorm.DB, opts ...gen.DOOption) runAutomation {
	_runAutomation := runAutomation{}

	_runAutomation.runAutomationDo.UseDB(db, opts...)
	_runAutomation.runAutomationDo.UseModel(&model.RunAutomation{})

	tableName := _runAutomation.runAutomationDo.TableName()
	_runAutomation.ALL = field.NewAsterisk(tableName)
	_runAutomation.AutomationID = field.NewString(tableName, "automation_id")
	_runAutomation.InstanceServerID = field.NewString(tableName, "instance_server_id")
	_runAutomation.InstanceServerChannelID = field.NewString(tableName, "instance_server_channel_id")
	_runAutomation.AutomationName = field.NewString(tableName, "automation_name")
	_runAutomation.IntervalType = field.NewString(tableName, "interval_type")
	_runAutomation.Time = field.NewTime(tableName, "time")
	_runAutomation.DayOfWeek = field.NewString(tableName, "day_of_week")
	_runAutomation.DayOfMonth = field.NewInt64(tableName, "day_of_month")
	_runAutomation.IsActive = field.NewBool(tableName, "is_active")
	_runAutomation.Created = field.NewTime(tableName, "created")
	_runAutomation.CreatedBy = field.NewString(tableName, "created_by")
	_runAutomation.LastUpd = field.NewTime(tableName, "last_upd")
	_runAutomation.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_runAutomation.fillFieldMap()

	return _runAutomation
}

type runAutomation struct {
	runAutomationDo runAutomationDo

	ALL                     field.Asterisk
	AutomationID            field.String
	InstanceServerID        field.String
	InstanceServerChannelID field.String
	AutomationName          field.String
	IntervalType            field.String
	Time                    field.Time
	DayOfWeek               field.String
	DayOfMonth              field.Int64
	IsActive                field.Bool
	Created                 field.Time
	CreatedBy               field.String
	LastUpd                 field.Time
	LastUpdBy               field.String

	fieldMap map[string]field.Expr
}

func (r runAutomation) Table(newTableName string) *runAutomation {
	r.runAutomationDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runAutomation) As(alias string) *runAutomation {
	r.runAutomationDo.DO = *(r.runAutomationDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runAutomation) updateTableName(table string) *runAutomation {
	r.ALL = field.NewAsterisk(table)
	r.AutomationID = field.NewString(table, "automation_id")
	r.InstanceServerID = field.NewString(table, "instance_server_id")
	r.InstanceServerChannelID = field.NewString(table, "instance_server_channel_id")
	r.AutomationName = field.NewString(table, "automation_name")
	r.IntervalType = field.NewString(table, "interval_type")
	r.Time = field.NewTime(table, "time")
	r.DayOfWeek = field.NewString(table, "day_of_week")
	r.DayOfMonth = field.NewInt64(table, "day_of_month")
	r.IsActive = field.NewBool(table, "is_active")
	r.Created = field.NewTime(table, "created")
	r.CreatedBy = field.NewString(table, "created_by")
	r.LastUpd = field.NewTime(table, "last_upd")
	r.LastUpdBy = field.NewString(table, "last_upd_by")

	r.fillFieldMap()

	return r
}

func (r *runAutomation) WithContext(ctx context.Context) IRunAutomationDo {
	return r.runAutomationDo.WithContext(ctx)
}

func (r runAutomation) TableName() string { return r.runAutomationDo.TableName() }

func (r runAutomation) Alias() string { return r.runAutomationDo.Alias() }

func (r runAutomation) Columns(cols ...field.Expr) gen.Columns {
	return r.runAutomationDo.Columns(cols...)
}

func (r *runAutomation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runAutomation) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["automation_id"] = r.AutomationID
	r.fieldMap["instance_server_id"] = r.InstanceServerID
	r.fieldMap["instance_server_channel_id"] = r.InstanceServerChannelID
	r.fieldMap["automation_name"] = r.AutomationName
	r.fieldMap["interval_type"] = r.IntervalType
	r.fieldMap["time"] = r.Time
	r.fieldMap["day_of_week"] = r.DayOfWeek
	r.fieldMap["day_of_month"] = r.DayOfMonth
	r.fieldMap["is_active"] = r.IsActive
	r.fieldMap["created"] = r.Created
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["last_upd"] = r.LastUpd
	r.fieldMap["last_upd_by"] = r.LastUpdBy
}

func (r runAutomation) clone(db *gorm.DB) runAutomation {
	r.runAutomationDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runAutomation) replaceDB(db *gorm.DB) runAutomation {
	r.runAutomationDo.ReplaceDB(db)
	return r
}

type runAutomationDo struct{ gen.DO }

type IRunAutomationDo interface {
	gen.SubQuery
	Debug() IRunAutomationDo
	WithContext(ctx context.Context) IRunAutomationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunAutomationDo
	WriteDB() IRunAutomationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunAutomationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunAutomationDo
	Not(conds ...gen.Condition) IRunAutomationDo
	Or(conds ...gen.Condition) IRunAutomationDo
	Select(conds ...field.Expr) IRunAutomationDo
	Where(conds ...gen.Condition) IRunAutomationDo
	Order(conds ...field.Expr) IRunAutomationDo
	Distinct(cols ...field.Expr) IRunAutomationDo
	Omit(cols ...field.Expr) IRunAutomationDo
	Join(table schema.Tabler, on ...field.Expr) IRunAutomationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationDo
	Group(cols ...field.Expr) IRunAutomationDo
	Having(conds ...gen.Condition) IRunAutomationDo
	Limit(limit int) IRunAutomationDo
	Offset(offset int) IRunAutomationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationDo
	Unscoped() IRunAutomationDo
	Create(values ...*model.RunAutomation) error
	CreateInBatches(values []*model.RunAutomation, batchSize int) error
	Save(values ...*model.RunAutomation) error
	First() (*model.RunAutomation, error)
	Take() (*model.RunAutomation, error)
	Last() (*model.RunAutomation, error)
	Find() ([]*model.RunAutomation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomation, err error)
	FindInBatches(result *[]*model.RunAutomation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunAutomation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunAutomationDo
	Assign(attrs ...field.AssignExpr) IRunAutomationDo
	Joins(fields ...field.RelationField) IRunAutomationDo
	Preload(fields ...field.RelationField) IRunAutomationDo
	FirstOrInit() (*model.RunAutomation, error)
	FirstOrCreate() (*model.RunAutomation, error)
	FindByPage(offset int, limit int) (result []*model.RunAutomation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunAutomationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runAutomationDo) Debug() IRunAutomationDo {
	return r.withDO(r.DO.Debug())
}

func (r runAutomationDo) WithContext(ctx context.Context) IRunAutomationDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runAutomationDo) ReadDB() IRunAutomationDo {
	return r.Clauses(dbresolver.Read)
}

func (r runAutomationDo) WriteDB() IRunAutomationDo {
	return r.Clauses(dbresolver.Write)
}

func (r runAutomationDo) Session(config *gorm.Session) IRunAutomationDo {
	return r.withDO(r.DO.Session(config))
}

func (r runAutomationDo) Clauses(conds ...clause.Expression) IRunAutomationDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runAutomationDo) Returning(value interface{}, columns ...string) IRunAutomationDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runAutomationDo) Not(conds ...gen.Condition) IRunAutomationDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runAutomationDo) Or(conds ...gen.Condition) IRunAutomationDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runAutomationDo) Select(conds ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runAutomationDo) Where(conds ...gen.Condition) IRunAutomationDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runAutomationDo) Order(conds ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runAutomationDo) Distinct(cols ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runAutomationDo) Omit(cols ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runAutomationDo) Join(table schema.Tabler, on ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runAutomationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runAutomationDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runAutomationDo) Group(cols ...field.Expr) IRunAutomationDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runAutomationDo) Having(conds ...gen.Condition) IRunAutomationDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runAutomationDo) Limit(limit int) IRunAutomationDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runAutomationDo) Offset(offset int) IRunAutomationDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runAutomationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runAutomationDo) Unscoped() IRunAutomationDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runAutomationDo) Create(values ...*model.RunAutomation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runAutomationDo) CreateInBatches(values []*model.RunAutomation, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runAutomationDo) Save(values ...*model.RunAutomation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runAutomationDo) First() (*model.RunAutomation, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomation), nil
	}
}

func (r runAutomationDo) Take() (*model.RunAutomation, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomation), nil
	}
}

func (r runAutomationDo) Last() (*model.RunAutomation, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomation), nil
	}
}

func (r runAutomationDo) Find() ([]*model.RunAutomation, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunAutomation), err
}

func (r runAutomationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomation, err error) {
	buf := make([]*model.RunAutomation, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runAutomationDo) FindInBatches(result *[]*model.RunAutomation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runAutomationDo) Attrs(attrs ...field.AssignExpr) IRunAutomationDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runAutomationDo) Assign(attrs ...field.AssignExpr) IRunAutomationDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runAutomationDo) Joins(fields ...field.RelationField) IRunAutomationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runAutomationDo) Preload(fields ...field.RelationField) IRunAutomationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runAutomationDo) FirstOrInit() (*model.RunAutomation, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomation), nil
	}
}

func (r runAutomationDo) FirstOrCreate() (*model.RunAutomation, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomation), nil
	}
}

func (r runAutomationDo) FindByPage(offset int, limit int) (result []*model.RunAutomation, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runAutomationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runAutomationDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runAutomationDo) Delete(models ...*model.RunAutomation) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runAutomationDo) withDO(do gen.Dao) *runAutomationDo {
	r.DO = *do.(*gen.DO)
	return r
}
