// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newRunAutomationTarget(db *gorm.DB, opts ...gen.DOOption) runAutomationTarget {
	_runAutomationTarget := runAutomationTarget{}

	_runAutomationTarget.runAutomationTargetDo.UseDB(db, opts...)
	_runAutomationTarget.runAutomationTargetDo.UseModel(&model.RunAutomationTarget{})

	tableName := _runAutomationTarget.runAutomationTargetDo.TableName()
	_runAutomationTarget.ALL = field.NewAsterisk(tableName)
	_runAutomationTarget.AutomationTargetID = field.NewString(tableName, "automation_target_id")
	_runAutomationTarget.AutomationID = field.NewString(tableName, "automation_id")
	_runAutomationTarget.CompanyID = field.NewString(tableName, "company_id")
	_runAutomationTarget.BranchID = field.NewString(tableName, "branch_id")
	_runAutomationTarget.DepartmentID = field.NewString(tableName, "department_id")
	_runAutomationTarget.DivisionID = field.NewString(tableName, "division_id")
	_runAutomationTarget.SectionID = field.NewString(tableName, "section_id")
	_runAutomationTarget.SectionLv01ID = field.NewString(tableName, "section_lv01_id")
	_runAutomationTarget.SectionLv02ID = field.NewString(tableName, "section_lv02_id")
	_runAutomationTarget.SectionLv03ID = field.NewString(tableName, "section_lv03_id")
	_runAutomationTarget.SectionLv04ID = field.NewString(tableName, "section_lv04_id")
	_runAutomationTarget.SectionLv05ID = field.NewString(tableName, "section_lv05_id")
	_runAutomationTarget.PositionID = field.NewString(tableName, "position_id")
	_runAutomationTarget.EmployeeTypeCode = field.NewString(tableName, "employee_type_code")
	_runAutomationTarget.EmployeeID = field.NewString(tableName, "employee_id")
	_runAutomationTarget.Created = field.NewTime(tableName, "created")
	_runAutomationTarget.CreatedBy = field.NewString(tableName, "created_by")
	_runAutomationTarget.LastUpd = field.NewTime(tableName, "last_upd")
	_runAutomationTarget.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_runAutomationTarget.fillFieldMap()

	return _runAutomationTarget
}

type runAutomationTarget struct {
	runAutomationTargetDo runAutomationTargetDo

	ALL                field.Asterisk
	AutomationTargetID field.String
	AutomationID       field.String
	CompanyID          field.String
	BranchID           field.String
	DepartmentID       field.String
	DivisionID         field.String
	SectionID          field.String
	SectionLv01ID      field.String
	SectionLv02ID      field.String
	SectionLv03ID      field.String
	SectionLv04ID      field.String
	SectionLv05ID      field.String
	PositionID         field.String
	EmployeeTypeCode   field.String
	EmployeeID         field.String
	Created            field.Time
	CreatedBy          field.String
	LastUpd            field.Time
	LastUpdBy          field.String

	fieldMap map[string]field.Expr
}

func (r runAutomationTarget) Table(newTableName string) *runAutomationTarget {
	r.runAutomationTargetDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runAutomationTarget) As(alias string) *runAutomationTarget {
	r.runAutomationTargetDo.DO = *(r.runAutomationTargetDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runAutomationTarget) updateTableName(table string) *runAutomationTarget {
	r.ALL = field.NewAsterisk(table)
	r.AutomationTargetID = field.NewString(table, "automation_target_id")
	r.AutomationID = field.NewString(table, "automation_id")
	r.CompanyID = field.NewString(table, "company_id")
	r.BranchID = field.NewString(table, "branch_id")
	r.DepartmentID = field.NewString(table, "department_id")
	r.DivisionID = field.NewString(table, "division_id")
	r.SectionID = field.NewString(table, "section_id")
	r.SectionLv01ID = field.NewString(table, "section_lv01_id")
	r.SectionLv02ID = field.NewString(table, "section_lv02_id")
	r.SectionLv03ID = field.NewString(table, "section_lv03_id")
	r.SectionLv04ID = field.NewString(table, "section_lv04_id")
	r.SectionLv05ID = field.NewString(table, "section_lv05_id")
	r.PositionID = field.NewString(table, "position_id")
	r.EmployeeTypeCode = field.NewString(table, "employee_type_code")
	r.EmployeeID = field.NewString(table, "employee_id")
	r.Created = field.NewTime(table, "created")
	r.CreatedBy = field.NewString(table, "created_by")
	r.LastUpd = field.NewTime(table, "last_upd")
	r.LastUpdBy = field.NewString(table, "last_upd_by")

	r.fillFieldMap()

	return r
}

func (r *runAutomationTarget) WithContext(ctx context.Context) IRunAutomationTargetDo {
	return r.runAutomationTargetDo.WithContext(ctx)
}

func (r runAutomationTarget) TableName() string { return r.runAutomationTargetDo.TableName() }

func (r runAutomationTarget) Alias() string { return r.runAutomationTargetDo.Alias() }

func (r runAutomationTarget) Columns(cols ...field.Expr) gen.Columns {
	return r.runAutomationTargetDo.Columns(cols...)
}

func (r *runAutomationTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runAutomationTarget) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 19)
	r.fieldMap["automation_target_id"] = r.AutomationTargetID
	r.fieldMap["automation_id"] = r.AutomationID
	r.fieldMap["company_id"] = r.CompanyID
	r.fieldMap["branch_id"] = r.BranchID
	r.fieldMap["department_id"] = r.DepartmentID
	r.fieldMap["division_id"] = r.DivisionID
	r.fieldMap["section_id"] = r.SectionID
	r.fieldMap["section_lv01_id"] = r.SectionLv01ID
	r.fieldMap["section_lv02_id"] = r.SectionLv02ID
	r.fieldMap["section_lv03_id"] = r.SectionLv03ID
	r.fieldMap["section_lv04_id"] = r.SectionLv04ID
	r.fieldMap["section_lv05_id"] = r.SectionLv05ID
	r.fieldMap["position_id"] = r.PositionID
	r.fieldMap["employee_type_code"] = r.EmployeeTypeCode
	r.fieldMap["employee_id"] = r.EmployeeID
	r.fieldMap["created"] = r.Created
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["last_upd"] = r.LastUpd
	r.fieldMap["last_upd_by"] = r.LastUpdBy
}

func (r runAutomationTarget) clone(db *gorm.DB) runAutomationTarget {
	r.runAutomationTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runAutomationTarget) replaceDB(db *gorm.DB) runAutomationTarget {
	r.runAutomationTargetDo.ReplaceDB(db)
	return r
}

type runAutomationTargetDo struct{ gen.DO }

type IRunAutomationTargetDo interface {
	gen.SubQuery
	Debug() IRunAutomationTargetDo
	WithContext(ctx context.Context) IRunAutomationTargetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunAutomationTargetDo
	WriteDB() IRunAutomationTargetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunAutomationTargetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunAutomationTargetDo
	Not(conds ...gen.Condition) IRunAutomationTargetDo
	Or(conds ...gen.Condition) IRunAutomationTargetDo
	Select(conds ...field.Expr) IRunAutomationTargetDo
	Where(conds ...gen.Condition) IRunAutomationTargetDo
	Order(conds ...field.Expr) IRunAutomationTargetDo
	Distinct(cols ...field.Expr) IRunAutomationTargetDo
	Omit(cols ...field.Expr) IRunAutomationTargetDo
	Join(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo
	Group(cols ...field.Expr) IRunAutomationTargetDo
	Having(conds ...gen.Condition) IRunAutomationTargetDo
	Limit(limit int) IRunAutomationTargetDo
	Offset(offset int) IRunAutomationTargetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationTargetDo
	Unscoped() IRunAutomationTargetDo
	Create(values ...*model.RunAutomationTarget) error
	CreateInBatches(values []*model.RunAutomationTarget, batchSize int) error
	Save(values ...*model.RunAutomationTarget) error
	First() (*model.RunAutomationTarget, error)
	Take() (*model.RunAutomationTarget, error)
	Last() (*model.RunAutomationTarget, error)
	Find() ([]*model.RunAutomationTarget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationTarget, err error)
	FindInBatches(result *[]*model.RunAutomationTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunAutomationTarget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunAutomationTargetDo
	Assign(attrs ...field.AssignExpr) IRunAutomationTargetDo
	Joins(fields ...field.RelationField) IRunAutomationTargetDo
	Preload(fields ...field.RelationField) IRunAutomationTargetDo
	FirstOrInit() (*model.RunAutomationTarget, error)
	FirstOrCreate() (*model.RunAutomationTarget, error)
	FindByPage(offset int, limit int) (result []*model.RunAutomationTarget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunAutomationTargetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runAutomationTargetDo) Debug() IRunAutomationTargetDo {
	return r.withDO(r.DO.Debug())
}

func (r runAutomationTargetDo) WithContext(ctx context.Context) IRunAutomationTargetDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runAutomationTargetDo) ReadDB() IRunAutomationTargetDo {
	return r.Clauses(dbresolver.Read)
}

func (r runAutomationTargetDo) WriteDB() IRunAutomationTargetDo {
	return r.Clauses(dbresolver.Write)
}

func (r runAutomationTargetDo) Session(config *gorm.Session) IRunAutomationTargetDo {
	return r.withDO(r.DO.Session(config))
}

func (r runAutomationTargetDo) Clauses(conds ...clause.Expression) IRunAutomationTargetDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runAutomationTargetDo) Returning(value interface{}, columns ...string) IRunAutomationTargetDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runAutomationTargetDo) Not(conds ...gen.Condition) IRunAutomationTargetDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runAutomationTargetDo) Or(conds ...gen.Condition) IRunAutomationTargetDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runAutomationTargetDo) Select(conds ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runAutomationTargetDo) Where(conds ...gen.Condition) IRunAutomationTargetDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runAutomationTargetDo) Order(conds ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runAutomationTargetDo) Distinct(cols ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runAutomationTargetDo) Omit(cols ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runAutomationTargetDo) Join(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runAutomationTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runAutomationTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runAutomationTargetDo) Group(cols ...field.Expr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runAutomationTargetDo) Having(conds ...gen.Condition) IRunAutomationTargetDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runAutomationTargetDo) Limit(limit int) IRunAutomationTargetDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runAutomationTargetDo) Offset(offset int) IRunAutomationTargetDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runAutomationTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationTargetDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runAutomationTargetDo) Unscoped() IRunAutomationTargetDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runAutomationTargetDo) Create(values ...*model.RunAutomationTarget) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runAutomationTargetDo) CreateInBatches(values []*model.RunAutomationTarget, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runAutomationTargetDo) Save(values ...*model.RunAutomationTarget) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runAutomationTargetDo) First() (*model.RunAutomationTarget, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationTarget), nil
	}
}

func (r runAutomationTargetDo) Take() (*model.RunAutomationTarget, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationTarget), nil
	}
}

func (r runAutomationTargetDo) Last() (*model.RunAutomationTarget, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationTarget), nil
	}
}

func (r runAutomationTargetDo) Find() ([]*model.RunAutomationTarget, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunAutomationTarget), err
}

func (r runAutomationTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationTarget, err error) {
	buf := make([]*model.RunAutomationTarget, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runAutomationTargetDo) FindInBatches(result *[]*model.RunAutomationTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runAutomationTargetDo) Attrs(attrs ...field.AssignExpr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runAutomationTargetDo) Assign(attrs ...field.AssignExpr) IRunAutomationTargetDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runAutomationTargetDo) Joins(fields ...field.RelationField) IRunAutomationTargetDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runAutomationTargetDo) Preload(fields ...field.RelationField) IRunAutomationTargetDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runAutomationTargetDo) FirstOrInit() (*model.RunAutomationTarget, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationTarget), nil
	}
}

func (r runAutomationTargetDo) FirstOrCreate() (*model.RunAutomationTarget, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationTarget), nil
	}
}

func (r runAutomationTargetDo) FindByPage(offset int, limit int) (result []*model.RunAutomationTarget, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runAutomationTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runAutomationTargetDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runAutomationTargetDo) Delete(models ...*model.RunAutomationTarget) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runAutomationTargetDo) withDO(do gen.Dao) *runAutomationTargetDo {
	r.DO = *do.(*gen.DO)
	return r
}
