// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"automation-engine/internal/domain/model"
)

func newRunAutomationAction(db *gorm.DB, opts ...gen.DOOption) runAutomationAction {
	_runAutomationAction := runAutomationAction{}

	_runAutomationAction.runAutomationActionDo.UseDB(db, opts...)
	_runAutomationAction.runAutomationActionDo.UseModel(&model.RunAutomationAction{})

	tableName := _runAutomationAction.runAutomationActionDo.TableName()
	_runAutomationAction.ALL = field.NewAsterisk(tableName)
	_runAutomationAction.AutomationActionID = field.NewString(tableName, "automation_action_id")
	_runAutomationAction.AutomationID = field.NewString(tableName, "automation_id")
	_runAutomationAction.ActionID = field.NewString(tableName, "action_id")
	_runAutomationAction.ConfigJSON = field.NewString(tableName, "config_json")
	_runAutomationAction.SortOrder = field.NewInt64(tableName, "sort_order")
	_runAutomationAction.Created = field.NewTime(tableName, "created")
	_runAutomationAction.CreatedBy = field.NewString(tableName, "created_by")
	_runAutomationAction.LastUpd = field.NewTime(tableName, "last_upd")
	_runAutomationAction.LastUpdBy = field.NewString(tableName, "last_upd_by")

	_runAutomationAction.fillFieldMap()

	return _runAutomationAction
}

type runAutomationAction struct {
	runAutomationActionDo runAutomationActionDo

	ALL                field.Asterisk
	AutomationActionID field.String
	AutomationID       field.String
	ActionID           field.String
	ConfigJSON         field.String
	SortOrder          field.Int64
	Created            field.Time
	CreatedBy          field.String
	LastUpd            field.Time
	LastUpdBy          field.String

	fieldMap map[string]field.Expr
}

func (r runAutomationAction) Table(newTableName string) *runAutomationAction {
	r.runAutomationActionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runAutomationAction) As(alias string) *runAutomationAction {
	r.runAutomationActionDo.DO = *(r.runAutomationActionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runAutomationAction) updateTableName(table string) *runAutomationAction {
	r.ALL = field.NewAsterisk(table)
	r.AutomationActionID = field.NewString(table, "automation_action_id")
	r.AutomationID = field.NewString(table, "automation_id")
	r.ActionID = field.NewString(table, "action_id")
	r.ConfigJSON = field.NewString(table, "config_json")
	r.SortOrder = field.NewInt64(table, "sort_order")
	r.Created = field.NewTime(table, "created")
	r.CreatedBy = field.NewString(table, "created_by")
	r.LastUpd = field.NewTime(table, "last_upd")
	r.LastUpdBy = field.NewString(table, "last_upd_by")

	r.fillFieldMap()

	return r
}

func (r *runAutomationAction) WithContext(ctx context.Context) IRunAutomationActionDo {
	return r.runAutomationActionDo.WithContext(ctx)
}

func (r runAutomationAction) TableName() string { return r.runAutomationActionDo.TableName() }

func (r runAutomationAction) Alias() string { return r.runAutomationActionDo.Alias() }

func (r runAutomationAction) Columns(cols ...field.Expr) gen.Columns {
	return r.runAutomationActionDo.Columns(cols...)
}

func (r *runAutomationAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runAutomationAction) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["automation_action_id"] = r.AutomationActionID
	r.fieldMap["automation_id"] = r.AutomationID
	r.fieldMap["action_id"] = r.ActionID
	r.fieldMap["config_json"] = r.ConfigJSON
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["created"] = r.Created
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["last_upd"] = r.LastUpd
	r.fieldMap["last_upd_by"] = r.LastUpdBy
}

func (r runAutomationAction) clone(db *gorm.DB) runAutomationAction {
	r.runAutomationActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runAutomationAction) replaceDB(db *gorm.DB) runAutomationAction {
	r.runAutomationActionDo.ReplaceDB(db)
	return r
}

type runAutomationActionDo struct{ gen.DO }

type IRunAutomationActionDo interface {
	gen.SubQuery
	Debug() IRunAutomationActionDo
	WithContext(ctx context.Context) IRunAutomationActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunAutomationActionDo
	WriteDB() IRunAutomationActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunAutomationActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunAutomationActionDo
	Not(conds ...gen.Condition) IRunAutomationActionDo
	Or(conds ...gen.Condition) IRunAutomationActionDo
	Select(conds ...field.Expr) IRunAutomationActionDo
	Where(conds ...gen.Condition) IRunAutomationActionDo
	Order(conds ...field.Expr) IRunAutomationActionDo
	Distinct(cols ...field.Expr) IRunAutomationActionDo
	Omit(cols ...field.Expr) IRunAutomationActionDo
	Join(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo
	Group(cols ...field.Expr) IRunAutomationActionDo
	Having(conds ...gen.Condition) IRunAutomationActionDo
	Limit(limit int) IRunAutomationActionDo
	Offset(offset int) IRunAutomationActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationActionDo
	Unscoped() IRunAutomationActionDo
	Create(values ...*model.RunAutomationAction) error
	CreateInBatches(values []*model.RunAutomationAction, batchSize int) error
	Save(values ...*model.RunAutomationAction) error
	First() (*model.RunAutomationAction, error)
	Take() (*model.RunAutomationAction, error)
	Last() (*model.RunAutomationAction, error)
	Find() ([]*model.RunAutomationAction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationAction, err error)
	FindInBatches(result *[]*model.RunAutomationAction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunAutomationAction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunAutomationActionDo
	Assign(attrs ...field.AssignExpr) IRunAutomationActionDo
	Joins(fields ...field.RelationField) IRunAutomationActionDo
	Preload(fields ...field.RelationField) IRunAutomationActionDo
	FirstOrInit() (*model.RunAutomationAction, error)
	FirstOrCreate() (*model.RunAutomationAction, error)
	FindByPage(offset int, limit int) (result []*model.RunAutomationAction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunAutomationActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runAutomationActionDo) Debug() IRunAutomationActionDo {
	return r.withDO(r.DO.Debug())
}

func (r runAutomationActionDo) WithContext(ctx context.Context) IRunAutomationActionDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runAutomationActionDo) ReadDB() IRunAutomationActionDo {
	return r.Clauses(dbresolver.Read)
}

func (r runAutomationActionDo) WriteDB() IRunAutomationActionDo {
	return r.Clauses(dbresolver.Write)
}

func (r runAutomationActionDo) Session(config *gorm.Session) IRunAutomationActionDo {
	return r.withDO(r.DO.Session(config))
}

func (r runAutomationActionDo) Clauses(conds ...clause.Expression) IRunAutomationActionDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runAutomationActionDo) Returning(value interface{}, columns ...string) IRunAutomationActionDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runAutomationActionDo) Not(conds ...gen.Condition) IRunAutomationActionDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runAutomationActionDo) Or(conds ...gen.Condition) IRunAutomationActionDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runAutomationActionDo) Select(conds ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runAutomationActionDo) Where(conds ...gen.Condition) IRunAutomationActionDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runAutomationActionDo) Order(conds ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runAutomationActionDo) Distinct(cols ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runAutomationActionDo) Omit(cols ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runAutomationActionDo) Join(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runAutomationActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runAutomationActionDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runAutomationActionDo) Group(cols ...field.Expr) IRunAutomationActionDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runAutomationActionDo) Having(conds ...gen.Condition) IRunAutomationActionDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runAutomationActionDo) Limit(limit int) IRunAutomationActionDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runAutomationActionDo) Offset(offset int) IRunAutomationActionDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runAutomationActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunAutomationActionDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runAutomationActionDo) Unscoped() IRunAutomationActionDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runAutomationActionDo) Create(values ...*model.RunAutomationAction) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runAutomationActionDo) CreateInBatches(values []*model.RunAutomationAction, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runAutomationActionDo) Save(values ...*model.RunAutomationAction) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runAutomationActionDo) First() (*model.RunAutomationAction, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationAction), nil
	}
}

func (r runAutomationActionDo) Take() (*model.RunAutomationAction, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationAction), nil
	}
}

func (r runAutomationActionDo) Last() (*model.RunAutomationAction, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationAction), nil
	}
}

func (r runAutomationActionDo) Find() ([]*model.RunAutomationAction, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunAutomationAction), err
}

func (r runAutomationActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunAutomationAction, err error) {
	buf := make([]*model.RunAutomationAction, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runAutomationActionDo) FindInBatches(result *[]*model.RunAutomationAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runAutomationActionDo) Attrs(attrs ...field.AssignExpr) IRunAutomationActionDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runAutomationActionDo) Assign(attrs ...field.AssignExpr) IRunAutomationActionDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runAutomationActionDo) Joins(fields ...field.RelationField) IRunAutomationActionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runAutomationActionDo) Preload(fields ...field.RelationField) IRunAutomationActionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runAutomationActionDo) FirstOrInit() (*model.RunAutomationAction, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationAction), nil
	}
}

func (r runAutomationActionDo) FirstOrCreate() (*model.RunAutomationAction, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunAutomationAction), nil
	}
}

func (r runAutomationActionDo) FindByPage(offset int, limit int) (result []*model.RunAutomationAction, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runAutomationActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runAutomationActionDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runAutomationActionDo) Delete(models ...*model.RunAutomationAction) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runAutomationActionDo) withDO(do gen.Dao) *runAutomationActionDo {
	r.DO = *do.(*gen.DO)
	return r
}
