// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefOperator = "def_operators"

// DefOperator mapped from table <def_operators>
type DefOperator struct {
	OperatorID     string    `gorm:"column:operator_id;primaryKey" json:"operator_id"`
	OperatorSymbol string    `gorm:"column:operator_symbol" json:"operator_symbol"`
	OperatorName   string    `gorm:"column:operator_name" json:"operator_name"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	Created        time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy      string    `gorm:"column:created_by" json:"created_by"`
	LastUpd        time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy      string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName DefOperator's table name
func (*DefOperator) TableName() string {
	return TableNameDefOperator
}
