// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefAction = "def_actions"

// DefAction mapped from table <def_actions>
type DefAction struct {
	ActionID     string    `gorm:"column:action_id;primaryKey" json:"action_id"`
	ActionCode   string    `gorm:"column:action_code" json:"action_code"`
	ActionName   string    `gorm:"column:action_name" json:"action_name"`
	ActionType   string    `gorm:"column:action_type;not null" json:"action_type"`
	InvokeURL    string    `gorm:"column:invoke_url" json:"invoke_url"`
	InvokeMethod string    `gorm:"column:invoke_method;not null;default:POST" json:"invoke_method"`
	InvokeType   string    `gorm:"column:invoke_type;not null;default:sync" json:"invoke_type"`
	Status       string    `gorm:"column:status;not null" json:"status"`
	Created      time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy    string    `gorm:"column:created_by" json:"created_by"`
	LastUpd      time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy    string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName DefAction's table name
func (*DefAction) TableName() string {
	return TableNameDefAction
}
