// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefUnit = "def_units"

// DefUnit mapped from table <def_units>
type DefUnit struct {
	UnitID    string    `gorm:"column:unit_id;primaryKey" json:"unit_id"`
	UnitCode  string    `gorm:"column:unit_code" json:"unit_code"`
	UnitName  string    `gorm:"column:unit_name" json:"unit_name"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	Created   time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy string    `gorm:"column:created_by" json:"created_by"`
	LastUpd   time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName DefUnit's table name
func (*DefUnit) TableName() string {
	return TableNameDefUnit
}
