// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefGroup = "def_groups"

// DefGroup mapped from table <def_groups>
type DefGroup struct {
	GroupID   string    `gorm:"column:group_id;primaryKey" json:"group_id"`
	GroupCode string    `gorm:"column:group_code" json:"group_code"`
	GroupName string    `gorm:"column:group_name" json:"group_name"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	CreatedBy string    `gorm:"column:created_by" json:"created_by"`
	Created   time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	LastUpdBy string    `gorm:"column:last_upd_by" json:"last_upd_by"`
	LastUpd   time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
}

// TableName DefGroup's table name
func (*DefGroup) TableName() string {
	return TableNameDefGroup
}
