// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefCondition = "def_conditions"

// DefCondition mapped from table <def_conditions>
type DefCondition struct {
	ConditionID   string    `gorm:"column:condition_id;primaryKey" json:"condition_id"`
	ConditionCode string    `gorm:"column:condition_code" json:"condition_code"`
	ConditionName string    `gorm:"column:condition_name" json:"condition_name"`
	ConditionType string    `gorm:"column:condition_type;not null" json:"condition_type"`
	Status        string    `gorm:"column:status;not null" json:"status"`
	Created       time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy     string    `gorm:"column:created_by" json:"created_by"`
	LastUpd       time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy     string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName DefCondition's table name
func (*DefCondition) TableName() string {
	return TableNameDefCondition
}
