// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePolicyGroupCondition = "policy_group_conditions"

// PolicyGroupCondition mapped from table <policy_group_conditions>
type PolicyGroupCondition struct {
	GroupID     string    `gorm:"column:group_id;primaryKey" json:"group_id"`
	ConditionID string    `gorm:"column:condition_id;primaryKey" json:"condition_id"`
	Created     time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy   string    `gorm:"column:created_by" json:"created_by"`
}

// TableName PolicyGroupCondition's table name
func (*PolicyGroupCondition) TableName() string {
	return TableNamePolicyGroupCondition
}
