// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePolicyConditionOperator = "policy_condition_operators"

// PolicyConditionOperator mapped from table <policy_condition_operators>
type PolicyConditionOperator struct {
	ConditionID string    `gorm:"column:condition_id;primaryKey" json:"condition_id"`
	OperatorID  string    `gorm:"column:operator_id;primaryKey" json:"operator_id"`
	Created     time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy   string    `gorm:"column:created_by" json:"created_by"`
}

// TableName PolicyConditionOperator's table name
func (*PolicyConditionOperator) TableName() string {
	return TableNamePolicyConditionOperator
}
