// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePolicyConditionAction = "policy_condition_actions"

// PolicyConditionAction mapped from table <policy_condition_actions>
type PolicyConditionAction struct {
	MyRowID     int64     `gorm:"column:my_row_id;primaryKey;autoIncrement:true" json:"my_row_id"`
	ConditionID string    `gorm:"column:condition_id;not null" json:"condition_id"`
	ActionID    string    `gorm:"column:action_id;not null" json:"action_id"`
	Created     time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy   string    `gorm:"column:created_by" json:"created_by"`
}

// TableName PolicyConditionAction's table name
func (*PolicyConditionAction) TableName() string {
	return TableNamePolicyConditionAction
}
