// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePolicyConditionUnit = "policy_condition_units"

// PolicyConditionUnit mapped from table <policy_condition_units>
type PolicyConditionUnit struct {
	ConditionID string    `gorm:"column:condition_id;primaryKey" json:"condition_id"`
	UnitID      string    `gorm:"column:unit_id;primaryKey" json:"unit_id"`
	Created     time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy   string    `gorm:"column:created_by" json:"created_by"`
}

// TableName PolicyConditionUnit's table name
func (*PolicyConditionUnit) TableName() string {
	return TableNamePolicyConditionUnit
}
