// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePolicyGroupAction = "policy_group_actions"

// PolicyGroupAction mapped from table <policy_group_actions>
type PolicyGroupAction struct {
	GroupID   string    `gorm:"column:group_id;primaryKey" json:"group_id"`
	ActionID  string    `gorm:"column:action_id;primaryKey" json:"action_id"`
	Created   time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy string    `gorm:"column:created_by" json:"created_by"`
}

// TableName PolicyGroupAction's table name
func (*PolicyGroupAction) TableName() string {
	return TableNamePolicyGroupAction
}
