// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRunAutomationTarget = "run_automation_targets"

// RunAutomationTarget mapped from table <run_automation_targets>
type RunAutomationTarget struct {
	AutomationTargetID string    `gorm:"column:automation_target_id;primaryKey" json:"automation_target_id"`
	AutomationID       string    `gorm:"column:automation_id" json:"automation_id"`
	CompanyID          string    `gorm:"column:company_id" json:"company_id"`
	BranchID           string    `gorm:"column:branch_id" json:"branch_id"`
	DepartmentID       string    `gorm:"column:department_id" json:"department_id"`
	DivisionID         string    `gorm:"column:division_id" json:"division_id"`
	SectionID          string    `gorm:"column:section_id" json:"section_id"`
	SectionLv01ID      string    `gorm:"column:section_lv01_id" json:"section_lv01_id"`
	SectionLv02ID      string    `gorm:"column:section_lv02_id" json:"section_lv02_id"`
	SectionLv03ID      string    `gorm:"column:section_lv03_id" json:"section_lv03_id"`
	SectionLv04ID      string    `gorm:"column:section_lv04_id" json:"section_lv04_id"`
	SectionLv05ID      string    `gorm:"column:section_lv05_id" json:"section_lv05_id"`
	PositionID         string    `gorm:"column:position_id" json:"position_id"`
	EmployeeTypeCode   string    `gorm:"column:employee_type_code" json:"employee_type_code"`
	EmployeeID         string    `gorm:"column:employee_id" json:"employee_id"`
	Created            time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy          string    `gorm:"column:created_by" json:"created_by"`
	LastUpd            time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy          string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName RunAutomationTarget's table name
func (*RunAutomationTarget) TableName() string {
	return TableNameRunAutomationTarget
}
