// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRunAutomationAction = "run_automation_actions"

// RunAutomationAction mapped from table <run_automation_actions>
type RunAutomationAction struct {
	AutomationActionID string    `gorm:"column:automation_action_id;primaryKey" json:"automation_action_id"`
	AutomationID       string    `gorm:"column:automation_id" json:"automation_id"`
	ActionID           string    `gorm:"column:action_id" json:"action_id"`
	ConfigJSON         string    `gorm:"column:config_json" json:"config_json"`
	SortOrder          int64     `gorm:"column:sort_order;not null" json:"sort_order"`
	Created            time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy          string    `gorm:"column:created_by" json:"created_by"`
	LastUpd            time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy          string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName RunAutomationAction's table name
func (*RunAutomationAction) TableName() string {
	return TableNameRunAutomationAction
}
