// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRunAutomationConditionGroup = "run_automation_condition_groups"

// RunAutomationConditionGroup mapped from table <run_automation_condition_groups>
type RunAutomationConditionGroup struct {
	AutomationConditionGroupID string    `gorm:"column:automation_condition_group_id;primaryKey" json:"automation_condition_group_id"`
	AutomationID               string    `gorm:"column:automation_id" json:"automation_id"`
	GroupOperator              string    `gorm:"column:group_operator" json:"group_operator"`
	SortOrder                  int32     `gorm:"column:sort_order" json:"sort_order"`
	Created                    time.Time `gorm:"column:created;not null;default:CURRENT_TIMESTAMP" json:"created"`
	CreatedBy                  string    `gorm:"column:created_by" json:"created_by"`
	LastUpd                    time.Time `gorm:"column:last_upd;not null;default:CURRENT_TIMESTAMP" json:"last_upd"`
	LastUpdBy                  string    `gorm:"column:last_upd_by" json:"last_upd_by"`
}

// TableName RunAutomationConditionGroup's table name
func (*RunAutomationConditionGroup) TableName() string {
	return TableNameRunAutomationConditionGroup
}
